'use strict';
window.initSuiteAdmin=async function({client,embedded=false,ownedCaps=[],isActive=()=>true,onBusy=()=>{},onDenied=()=>{}}={}){
 const $=id=>document.getElementById(id),cfg=window.LA_SUITE_CONFIG||{};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=v=>v?new Date(v.length===10?v+'T12:00:00':v).toLocaleDateString('fr-FR'):'—';const bytes=v=>Number(v)>=1e9?(Number(v)/1e9).toFixed(1)+' Go':Math.round(Number(v)/1e6)+' Mo';
 const states={draft:'En préparation',scheduled:'Prête à partager',open:'Dépôts ouverts',closed:'Dépôts terminés',full:'Stockage rempli',expired:'Conservation terminée',suspended:'Dépôts en pause',missing_date:'Date à compléter'};
 const backupStates={queued:'En attente',running:'Sauvegarde en cours',ready:'Sauvegarde prête',failed:'À réessayer',restoring:'Restauration en cours',restored:'Restaurée',importing:'Import en cours'};
 let clientFilter=null,exportsByCapsule=new Map();
 let data={capsules:[],clients:[],backups:[]},busy=false,authorized=false,timer=null;
 function status(text,error=false){if($('capsule-dialog').open&&$('detail-export-status'))$('detail-export-status').textContent=text;$('admin-status').textContent=text;$('admin-status').className='status show '+(error?'err':'ok');}
 function setBusy(value){busy=value;onBusy(value);document.querySelectorAll('#admin-content button:not([data-tab]),#capsule-dialog button:not(.dialog-close),#workspace-administration .workspace-service-tools button').forEach(b=>b.disabled=value);}
 window.addEventListener('hashchange',()=>{if(/^[a-f0-9]{64}$/.test(new URLSearchParams(location.hash.slice(1)).get('invite')||''))location.reload();});
 const inviteKey='la_suite_admin_invite';const hash=new URLSearchParams(location.hash.slice(1));let invite=null;if(/^[a-f0-9]{64}$/.test(hash.get('invite')||'')){invite={token:hash.get('invite'),at:Date.now()};try{localStorage.setItem(inviteKey,JSON.stringify(invite));history.replaceState(null,'',location.pathname)}catch{}}
 try{invite=invite||JSON.parse(localStorage.getItem(inviteKey)||'null');if(invite&&Date.now()-invite.at>48*3600000){localStorage.removeItem(inviteKey);invite=null;}}catch{}
 if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY||!window.supabase){$('access-message').textContent='Service indisponible. Rechargez la page.';return;}
 const sb=client||window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
 let sessionOwner=null;
 function clearPrivateView(){authorized=false;onBusy(false);clearTimeout(timer);data={capsules:[],clients:[],backups:[]};['capsule-cards','client-cards','backup-cards','admin-stats','capsule-detail'].forEach(id=>$(id).replaceChildren());$('admin-content').hidden=true;$('admin-access').hidden=false;$('access-message').textContent='Votre session est terminée. Reconnectez-vous.';$('admin-auth').hidden=false;$('admin-signup').hidden=true;if($('capsule-dialog').open)$('capsule-dialog').close();if($('confirm-dialog').open)$('confirm-dialog').dispatchEvent(new Event('cancel',{cancelable:true}));if(embedded)onDenied();}
 sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||sessionOwner&&session?.user?.id&&session.user.id!==sessionOwner)clearPrivateView()});
 async function api(action,payload={}){const {data,error}=await sb.functions.invoke('suite-admin',{body:{action,...payload}});if(error){if([401,403].includes(error.context?.status))clearPrivateView();let message=error.message;try{message=(await error.context.json()).error||message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
 async function confirmAction(title,text){$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm-dialog').showModal();return new Promise(resolve=>{function done(value){$('confirm-dialog').close();$('confirm-yes').onclick=null;$('confirm-no').onclick=null;$('confirm-dialog').oncancel=null;resolve(value);}$('confirm-yes').onclick=()=>done(true);$('confirm-no').onclick=()=>done(false);$('confirm-dialog').oncancel=()=>done(false);});}
 async function run(fn){if(busy||!authorized)return;setBusy(true);try{await fn();await refresh();}catch(e){status(e.message||'Opération impossible.',true);}finally{setBusy(false);}}
 function attention(c){return ['full','suspended','missing_date'].includes(c.usage.state)||c.usage.used_bytes>=c.usage.quota_bytes*.8;}
 function email(id){return data.clients.find(x=>x.id===id)?.email||'Compte indisponible';}
 function render(){
  $('admin-stats').innerHTML=[['Capsules',data.capsules.length],['Clients',data.clients.length],['À vérifier',data.capsules.filter(attention).length],['Fichiers clients',bytes(data.capsules.reduce((n,c)=>n+Number(c.usage.used_bytes),0))]].map(([name,value])=>`<div class="admin-stat"><strong>${esc(value)}</strong><span>${name}</span></div>`).join('');
  renderCapsules();updateExportState();$('client-cards').innerHTML=data.clients.map(c=>`<article class="admin-card admin-client"><div><strong>${esc(c.email||'Sans adresse')}</strong><p>${c.confirmed?'Adresse confirmée':'Adresse à confirmer'} · Inscrit le ${date(c.created_at)}</p></div><button class="btn secondary" data-client="${c.id}">${data.capsules.filter(x=>x.owner_id===c.id).length} capsule(s)</button></article>`).join('')||'<p class="admin-empty">Aucun client pour le moment.</p>';
  $('backup-cards').innerHTML=data.backups.map(b=>`<article class="admin-card admin-backup"><div><strong>${esc(b.label)}</strong><p>${date(b.created_at)} · ${b.automatic?'Automatique':'Manuelle'} · ${esc(backupStates[b.state])}${['running','restoring'].includes(b.state)?' · '+(b.state==='restoring'?b.restore_cursor:b.cursor)+' / '+b.total+' fichiers':''}</p>${b.error?'<p class="admin-error">'+esc(b.error)+'</p>':''}</div><div class="admin-actions">${['ready','restored'].includes(b.state)?`<button class="btn secondary" data-export="${b.id}">Télécharger</button><button class="btn secondary" data-restore="${b.id}">Restaurer</button>`:b.state==='failed'?`<button class="btn secondary" data-retry="${b.id}">Réessayer</button>`:''}</div></article>`).join('')||'<p class="admin-empty">La première sauvegarde automatique aura lieu cette nuit. Vous pouvez la lancer maintenant.</p>';
  $('backup-all').disabled=busy||!data.capsules.length;
 }
 function renderCapsules(){const caps=data.capsules.filter(c=>!clientFilter||c.owner_id===clientFilter);$('capsule-cards').innerHTML=caps.map(c=>`<article class="admin-card admin-capsule"><div class="admin-capsule-head"><div><h2>${esc(c.name)}</h2><p>${date(c.date)}</p></div><div class="admin-actions">${ownedCaps.some(own=>own.id===c.id)?`<a class="btn primary" href="dashboard.html?slug=${encodeURIComponent(ownedCaps.find(own=>own.id===c.id).slug)}">Ouvrir</a>`:""}<button class="btn secondary" data-capsule="${c.id}" aria-label="Paramètres de ${esc(c.name)}"><i class="fa-solid fa-sliders" aria-hidden="true"></i><span>Paramètres</span></button></div></div></article>`).join('')||'<p class="admin-empty">Aucune capsule pour le moment.</p>';}
 async function refreshServices(){
  try{const service=await api('services');$('offer-services').innerHTML=[['notifications','Notifications par e-mail',service.notifications_enabled,'Un récapitulatif des souvenirs ouverts par jour et deux rappels avant expiration.'],['payments','Achats et changements de formule',service.payments_enabled,'Achats de nouvelles capsules et paiement de la différence pour les formules supérieures. Les capsules déjà activées gratuitement conservent leurs droits.']].map(([key,label,enabled,note])=>'<p><strong>'+label+' : '+(enabled?'activés':service.configured[key]?'prêts à activer':'à configurer')+'</strong><br>'+note+'</p>'+(service.configured[key]?'<button type="button" class="btn secondary" data-service="'+key+'" data-enabled="'+enabled+'">'+(enabled?'Désactiver':'Activer')+'</button>':'')).join('')+'<p class="hint">'+Number(service.failed_notifications||0)+' notification(s) à vérifier · '+Number(service.refunds_to_check||0)+' remboursement(s) à vérifier.</p><p><a href="https://github.com/Orbivia/LA_SUITE_WEB/blob/main/SERVICE-SETUP.md" target="_blank" rel="noopener">Guide de configuration</a></p>';
   $('offer-services').querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>run(async()=>{const payload={[b.dataset.service+'_enabled']:b.dataset.enabled!=='true'};await api('configure_services',payload);await refreshServices();status('Réglage enregistré.');}));
  }catch(e){$('offer-services').textContent='Les services sont momentanément indisponibles. Actualisez la page.';}
 }
 function scheduleRefresh(){
  clearTimeout(timer);if(!authorized)return;timer=setTimeout(async()=>{if(!authorized)return;if(busy||!isActive()||document.visibilityState!=='visible'){scheduleRefresh();return}try{await refresh()}catch(e){status('Actualisation impossible. Cliquez sur Actualiser.',true);scheduleRefresh()}},15000);
 }
 async function refresh(){if(!authorized)return;data=await api('overview');if(!authorized)return;render();await refreshServices();if(busy)setBusy(true);scheduleRefresh();}

 function detail(id){const c=data.capsules.find(x=>x.id===id);if(!c)return;const quota=(c.quota_override||c.usage.quota_bytes)/1e9;$('capsule-detail').innerHTML=`<div class="eyebrow">Paramètres de la capsule</div><h2>${esc(c.name)}</h2><p>${esc(email(c.owner_id))} · ${date(c.date)}</p><dl class="admin-detail"><div><dt>Souvenirs reçus</dt><dd>${c.messages}</dd></div><div><dt>Stockage</dt><dd>${bytes(c.usage.used_bytes)} / ${bytes(c.usage.quota_bytes)}</dd></div><div><dt>Activation</dt><dd>${c.activation==='payment'?'Payante':c.activation?'Gratuite':'À activer'} · ${({photo:'Essentiel',audio:'Plus',premium:'Premium'})[c.plan]||'Premium'}</dd></div><div><dt>Conservation jusqu’au</dt><dd>${date(c.usage.expires_at)}</dd></div></dl><p class="hint">Les contenus et les souvenirs programmés restent dans l’espace du client.</p><div class="admin-actions"><button id="detail-backup" class="btn primary">Préparer l’export de cette capsule</button><button id="detail-download" class="btn secondary" hidden>Télécharger l’archive</button><p id="detail-export-status" class="hint" role="status"></p><button id="detail-suspend" class="btn secondary">${c.suspended?'Reprendre les dépôts':'Mettre les dépôts en pause'}</button></div><details class="admin-quota"><summary>Ajuster le stockage</summary><form id="quota-form"><label for="quota">Capacité totale (Go)</label><input id="quota" type="number" min="0.1" max="50" step="0.1" required value="${quota}"><button class="btn secondary" type="submit">Enregistrer</button></form></details>`;
  $('detail-backup').onclick=()=>run(async()=>{const job=await api('backup',{id});if(!job?.id)throw Error('L’export n’a pas pu être préparé.');exportsByCapsule.set(id,job.id);await api('tick');});
  $('detail-download').onclick=()=>run(()=>exportArchive(exportsByCapsule.get(id)));
  $('capsule-dialog').dataset.exportCapsule=id;updateExportState();
  $('detail-suspend').onclick=async()=>{if(!await confirmAction(c.suspended?'Reprendre les dépôts ?':'Mettre les dépôts en pause ?',c.suspended?'La période et les limites habituelles s’appliqueront.':'Les invités ne pourront plus déposer de souvenir. Les souvenirs existants sont conservés.'))return;await run(async()=>{await api('manage',{id,suspended:!c.suspended,quota:c.quota_override});$('capsule-dialog').close();status(c.suspended?'Les dépôts ont repris.':'Les dépôts sont en pause.');});};
  $('quota-form').onsubmit=e=>{e.preventDefault();run(async()=>{await api('manage',{id,suspended:c.suspended,quota:Math.round(Number($('quota').value)*1e9)});$('capsule-dialog').close();status('Stockage mis à jour.');});};$('capsule-dialog').showModal();
 }
 function updateExportState(){const id=$('capsule-dialog').dataset.exportCapsule,jobId=exportsByCapsule.get(id);if(!$('detail-download')||!jobId)return;const job=data.backups.find(b=>b.id===jobId),ready=job&&['ready','restored'].includes(job.state);$('detail-download').hidden=!ready;$('detail-backup').hidden=!!job&&job.state!=='failed';$('detail-export-status').textContent=ready?'Archive prête à télécharger.':job?.state==='failed'?'Export impossible. Vous pouvez réessayer.':'Préparation de l’archive en cours…';}
 async function exportArchive(id){
  const name='la-suite-'+new Date().toISOString().slice(0,10)+'.lasuite';let writable,parts=[],size=0,handle;
  // The file picker must run within the click gesture before any network request.
  if(window.showSaveFilePicker){handle=await window.showSaveFilePicker({suggestedName:name,types:[{description:'Archive La Suite',accept:{'application/octet-stream':['.lasuite']}}]});writable=await handle.createWritable();}
  else writable={write:async part=>{size+=part.size||part.byteLength;if(size>150000000)throw Error('Cette archive est volumineuse. Téléchargez-la depuis Chrome ou Edge sur ordinateur.');parts.push(part);},close:async()=>{const url=URL.createObjectURL(new Blob(parts,{type:'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},abort:async()=>{parts=[];}};
  try{await SuiteArchive.write(offset=>api('export',{id,offset}),writable,(i,total)=>status('Téléchargement : '+i+' / '+total+' fichiers…'));status('Archive téléchargée. Gardez-la en lieu sûr.');}catch(e){await writable.abort?.();throw e;}
 }
 async function importArchive(file){const entries=await SuiteArchive.entries(file),first=entries[0];if(!first||!first.name.endsWith('/manifest'))throw Error('Archive invalide.');if(!await confirmAction('Restaurer cette archive ?','Les éléments manquants seront remis en place. Les nouvelles contributions et les réglages existants seront conservés.'))return;
  await run(async()=>{const bytes=new Uint8Array(await first.blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const job=await api('import_start',{name:first.name,manifest:btoa(binary)});const byName=new Map(entries.slice(1).map(e=>[e.name,e.blob]));if(entries.length!==job.files.length+1)throw Error('Archive incomplète.');
   for(let i=0;i<job.files.length;i++){const f=job.files[i],blob=byName.get(f.key);if(!blob||blob.size!==f.size+28)throw Error('Archive incomplète.');const target=await api('import_url',{id:job.id,index:i});const {error}=await sb.storage.from('capsule-backups').uploadToSignedUrl(target.path,target.token,blob,{contentType:'application/octet-stream'});if(error)throw error;status('Import : '+(i+1)+' / '+job.files.length+' fichiers…');}
   await api('import_finish',{id:job.id});status('Restauration lancée. Elle continue même si vous fermez la page.');await api('tick');
  });
 }
 $('refresh').onclick=()=>run(async()=>{clientFilter=null;status('Liste actualisée.');});
 $('backup-all').onclick=()=>run(async()=>{await api('backup');status('Sauvegarde lancée. Elle continue en arrière-plan.');await api('tick');});
 $('import-backup').onclick=()=>{$('archive-input').value='';$('archive-input').click();};$('archive-input').onchange=async()=>{if($('archive-input').files[0])try{await importArchive($('archive-input').files[0]);}catch(e){status(e.message,true);}};
 const handleAdminClick=async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.capsule)detail(b.dataset.capsule);if(b.dataset.client){clientFilter=b.dataset.client;$('workspace-administration')?.close();$('panel-clients').parentElement.open=false;renderCapsules();$('workspace-capsules')?.showModal();}if(b.dataset.export)run(()=>exportArchive(b.dataset.export));if(b.dataset.restore){if(await confirmAction('Restaurer les éléments manquants ?','Les nouveaux souvenirs et les réglages actuels seront conservés. Les dates de dévoilement de la sauvegarde restent respectées.'))run(async()=>{await api('restore',{id:b.dataset.restore});status('Restauration lancée.');await api('tick');});}if(b.dataset.retry)run(async()=>{await api('retry',{id:b.dataset.retry});status('Opération relancée.');await api('tick');});};
 $('admin-content').onclick=handleAdminClick;document.querySelector('.workspace-service-tools').onclick=handleAdminClick;
 if($('admin-logout'))$('admin-logout').onclick=async()=>{if(busy){status('Patientez jusqu’à la fin de l’opération.',true);return;}clearTimeout(timer);await sb.auth.signOut();location.href='admin.html';};
 try{const {data:user,error}=await sb.auth.getUser();if(error||!user.user){$('access-message').textContent=invite?'Connectez-vous ou créez votre compte pour activer votre accès administrateur.':'Connectez-vous avec votre compte administrateur.';$('admin-auth').hidden=false;$('admin-signup').hidden=!invite;return;}
  const {data:member,error:memberError}=await sb.rpc('admin_status');if(memberError)throw memberError;if(member!==true){if(embedded){clearPrivateView();return;}if(!invite){$('access-message').textContent='Ce compte ne dispose pas d’un accès administrateur.';if($('admin-logout'))$('admin-logout').hidden=false;return;}const {error}=await sb.rpc('admin_claim',{p_token:invite.token});if(error)throw error;}
  try{localStorage.removeItem(inviteKey)}catch{}sessionOwner=user.user.id;authorized=true;if($('admin-logout'))$('admin-logout').hidden=false;$('admin-access').hidden=true;$('admin-content').hidden=false;await refresh();
 }catch(e){$('access-message').textContent=e.message||'Vérification impossible. Rechargez la page.';status(e.message,true);}
};
if(document.getElementById('admin-access'))window.initSuiteAdmin();

