'use strict';
window.initSuiteAdmin=async function({client,embedded=false,ownedCaps=[],isActive=()=>true,onBusy=()=>{},onDenied=()=>{}}={}){
 const $=id=>document.getElementById(id),cfg=window.LA_SUITE_CONFIG||{};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=v=>v?new Date(v.length===10?v+'T12:00:00':v).toLocaleDateString('fr-FR'):'—';const bytes=v=>Number(v)>=1e9?(Number(v)/1e9).toFixed(1)+' Go':Math.round(Number(v)/1e6)+' Mo';
 const states={draft:'En préparation',scheduled:'Prête à partager',open:'Dépôts ouverts',closed:'Dépôts terminés',full:'Stockage rempli',expired:'Conservation terminée',suspended:'Dépôts en pause',missing_date:'Date à compléter'};
 const backupStates={queued:'En attente',running:'Sauvegarde en cours',ready:'Sauvegarde prête',failed:'À réessayer',restoring:'Restauration en cours',restored:'Restaurée',importing:'Import en cours'};
 let backupScope='all',view='overview',rowDrafts=new Map(),sortDirection=1,sortKey='name',emailFilter='',stateFilter='all';
 let data={capsules:[],clients:[],backups:[]},busy=false,authorized=false,timer=null;
 function status(text,error=false){$('admin-status').textContent=text;$('admin-status').className=text?'status show '+(error?'err':'ok'):'status';}
 function setBusy(value){busy=value;onBusy(value);document.querySelectorAll('#admin-content button:not([data-tab]),#admin-content input,#admin-content select').forEach(b=>b.disabled=value||b.dataset.locked==='true');}
 window.addEventListener('hashchange',()=>{if(/^[a-f0-9]{64}$/.test(new URLSearchParams(location.hash.slice(1)).get('invite')||''))location.reload();});
 const inviteKey='la_suite_admin_invite';const hash=new URLSearchParams(location.hash.slice(1));let invite=null;if(/^[a-f0-9]{64}$/.test(hash.get('invite')||'')){invite={token:hash.get('invite'),at:Date.now()};try{localStorage.setItem(inviteKey,JSON.stringify(invite));history.replaceState(null,'',location.pathname)}catch{}}
 try{invite=invite||JSON.parse(localStorage.getItem(inviteKey)||'null');if(invite&&Date.now()-invite.at>48*3600000){localStorage.removeItem(inviteKey);invite=null;}}catch{}
 if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY||!window.supabase){$('access-message').textContent='Service indisponible. Rechargez la page.';return;}
 const sb=client||window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
 let sessionOwner=null,currentEmail='';
 const downloadSession=new AbortController();
 function clearPrivateView(){authorized=false;rowDrafts.clear();$('admin-email-form').reset();$('admin-password-form').reset();downloadSession.abort(new Error('Votre session est terminée. Reconnectez-vous.'));onBusy(false);clearTimeout(timer);data={capsules:[],clients:[],backups:[]};['capsule-cards','backup-cards','admin-stats','admin-account-email','offer-services','admin-sales-totals','admin-sales-chart','admin-backup-scope'].forEach(id=>$(id)?.replaceChildren());$('admin-content').hidden=true;$('admin-access').hidden=false;$('access-message').textContent='Votre session est terminée. Reconnectez-vous.';$('admin-auth').hidden=false;$('admin-signup').hidden=true;if($('confirm-dialog').open)$('confirm-dialog').dispatchEvent(new Event('cancel',{cancelable:true}));if(embedded)onDenied();}
 sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||sessionOwner&&session?.user?.id&&session.user.id!==sessionOwner)clearPrivateView();else if(event==='USER_UPDATED'&&session?.user?.email){currentEmail=session.user.email;$('admin-account-email').textContent=currentEmail;}});
 async function api(action,payload={}){if(downloadSession.signal.aborted)throw downloadSession.signal.reason;const {data,error}=await sb.functions.invoke('suite-admin',{body:{action,...payload}});if(downloadSession.signal.aborted)throw downloadSession.signal.reason;if(error){if([401,403].includes(error.context?.status))clearPrivateView();let message=error.message;try{message=(await error.context.json()).error||message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
 async function confirmAction(title,text){$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm-dialog').showModal();return new Promise(resolve=>{function done(value){$('confirm-dialog').close();$('confirm-yes').onclick=null;$('confirm-no').onclick=null;$('confirm-dialog').oncancel=null;resolve(value);}$('confirm-yes').onclick=()=>done(true);$('confirm-no').onclick=()=>done(false);$('confirm-dialog').oncancel=()=>done(false);});}
 async function run(fn){if(busy||!authorized)return;setBusy(true);try{await fn();await refresh();}catch(e){status(e.message||'Opération impossible.',true);}finally{setBusy(false);}}
 function attention(c){return ['full','suspended','missing_date'].includes(c.usage.state)||c.usage.used_bytes>=c.usage.quota_bytes*.8;}
 function email(id){return data.clients.find(x=>x.id===id)?.email||'Compte indisponible';}
 function render(){
  $('admin-stats').innerHTML=[['Capsules',data.capsules.length],['Clients',data.clients.filter(c=>!c.is_admin).length],['Capsules à surveiller',data.capsules.filter(attention).length],['Mo utilisés',(data.capsules.reduce((n,c)=>n+Number(c.usage.used_bytes),0)/1e6).toLocaleString('fr-FR',{maximumFractionDigits:1})]].map(([name,value])=>`<div class="admin-stat"><strong>${esc(value)}</strong><span>${name}</span>${name==='Capsules à surveiller'?'<small>Stockage ≥ 80 %, dépôts en pause ou date manquante.</small><button type="button" class="admin-text-button" data-attention="true">Voir les capsules</button>':''}</div>`).join('');
  renderCapsules();renderSales();renderBackups();

 }
 function selectView(next){
  if(!authorized||busy||!['overview','capsules','settings'].includes(next))return;
  view=next;document.querySelectorAll('[data-admin-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.adminView===view)));
  for(const key of ['overview','capsules','settings'])$('panel-'+key).hidden=key!==view;
 }
 function capsuleExpected(c){const u=c.usage;return {date:c.date,plan:c.plan,admin_plan_override:c.admin_plan_override??null,activated_at:c.activated_at??null,...Object.fromEntries(['opens_at','closes_at','delivery_before','expires_at','quota_bytes'].map(k=>[k,u[k]]))};}
 function dayCount(a,b){return Math.max(1,Math.round((new Date(b+'T12:00:00Z')-new Date(a+'T12:00:00Z'))/86400000)+1);}
 function addDays(a,n){const d=new Date(a+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
 const planDefaults={photo:{label:'Essentiel',quota:1},audio:{label:'Plus',quota:2},premium:{label:'Premium',quota:5}};
 function rowValues(c){const u=c.usage,open=parisDate(u.opens_at),close=parisDate(u.closes_at,true),end=u.access_until||parisDate(u.expires_at,true);const custom=u.custom_rules||Number(u.retention_years||3)!==3||c.quota_override!=null||u.legacy;return {plan:custom?'custom':u.effective_plan||c.plan,base:u.effective_plan||c.plan,event:c.date,email:email(c.owner_id),activation:parisDate(c.activated_at),deposit:String(dayCount(open,close)),quota:String(u.quota_bytes/1e9),storage:custom?String(Math.max(.1,Math.round((new Date(end+'T12:00:00Z')-new Date(c.date+'T12:00:00Z'))/86400000/365.25*10)/10)):'3',paused:c.suspended?'yes':'no'};}
 function renderCapsules(){
  const caps=data.capsules.filter(c=>(stateFilter==='all'||stateFilter==='attention'&&attention(c)||c.usage.state===stateFilter)&&email(c.owner_id).toLocaleLowerCase('fr').includes(emailFilter)).sort((a,b)=>{const value=c=>sortKey==='email'?email(c.owner_id):sortKey==='plan'?rowValues(c).plan:sortKey==='quota'?Number(c.usage.quota_bytes):sortKey==='deposit'?Number(rowValues(c).deposit):sortKey==='storage'?Number(rowValues(c).storage):c[sortKey]||'';const x=value(a),y=value(b);return sortDirection*((typeof x==='number'?x-y:String(x).localeCompare(String(y),'fr',{numeric:true,sensitivity:'base'}))||a.id.localeCompare(b.id));});
  const head=(key,label,extra='')=>`<th scope="col" aria-sort="${sortKey===key?(sortDirection===1?'ascending':'descending'):'none'}"><button type="button" data-sort="${key}">${label}${sortKey===key?(sortDirection===1?' ↑':' ↓'):''}</button>${extra}</th>`;
  const rows=caps.map(c=>{const draft=rowDrafts.get(c.id),v=draft?.values||rowValues(c),u=c.usage,custom=v.plan==='custom';
   const input=(key,type,extra='')=>`<input data-field="${key}" type="${type}" value="${esc(v[key])}" aria-label="${esc(({event:'Date de l’événement',email:'E-mail du client',activation:'Date d’activation',deposit:'Durée de dépôt en jours',quota:'Capacité en Go',storage:'Durée de stockage en années'})[key]+' · '+c.name)}" ${extra}>`;
   const lock=custom?'':'disabled data-locked="true"';
   return `<tr data-capsule-row="${c.id}"><td><strong>${esc(c.name)}</strong>${input('event','date','required')}<small class="admin-capsule-state">${esc(states[u.state]||'Indisponible')}</small><label class="admin-pause"><input data-field="paused" type="checkbox" ${v.paused==='yes'?'checked':''}> Dépôts en pause</label></td><td>${input('email','email','required maxlength="254"')}<p class="admin-row-status" role="status">${esc(draft?.error||'')}</p></td><td><select data-field="plan" aria-label="Formule · ${esc(c.name)}">${[...Object.entries(planDefaults).map(([key,d])=>[key,d.label]),['custom','Personnalisé']].map(([key,label])=>`<option value="${key}" ${v.plan===key?'selected':''}>${label}</option>`).join('')}</select>${custom?`<select data-field="base" aria-label="Formats · ${esc(c.name)}">${Object.entries(planDefaults).map(([key,d])=>`<option value="${key}" ${v.base===key?'selected':''}>${d.label}</option>`).join('')}</select>`:''}</td><td>${input('activation','date',c.status==='active'?'required max="'+parisDate(new Date().toISOString())+'"':'disabled data-locked="true"')}<small>${c.status==='active'?'':'Non activée'}</small></td><td>${input('deposit','number','required min="1" max="36525" step="1" '+lock)}</td><td>${input('quota','number','required min="'+Math.max(.1,Math.ceil(Number(u.used_bytes)/1e8)/10)+'" max="50" step="0.1" '+lock)}<small>${bytes(u.used_bytes)} utilisés</small></td><td>${input('storage','number','required min="0.1" max="100" step="0.1" '+lock)}</td><td class="admin-compact-actions"><button type="button" class="btn secondary" data-capsule-download="${c.id}" ${u.state==='expired'?'disabled data-locked="true"':''}>Télécharger</button><button type="button" class="admin-delete" data-capsule-delete="${c.id}">Supprimer</button></td></tr>`;});
  $('capsule-cards').innerHTML=`<table class="admin-capsules-table"><thead><tr>${head('name','Capsule',`<select id="admin-state-filter" aria-label="Filtrer par état"><option value="all">Tous les états</option><option value="attention">À surveiller</option><option value="draft">En préparation</option><option value="suspended">Dépôts en pause</option><option value="expired">Terminées</option></select>`)}${head('email','E-mail',`<input id="admin-email-filter" type="search" aria-label="Filtrer les e-mails" placeholder="Filtrer les e-mails" value="${esc(emailFilter)}">`)}${head('plan','Formule')}${head('activated_at','Activation')}${head('deposit','Dépôt (jours)')}${head('quota','Capacité (Go)')}${head('storage','Stockage (ans)')}<th scope="col">Actions</th></tr></thead><tbody>${rows.join('')||'<tr><td colspan="8" class="admin-empty">Aucune capsule.</td></tr>'}</tbody></table>`;
  $('admin-state-filter').value=stateFilter;
 }
 function renderSales(){
  const plans=[['photo','Essentiel'],['audio','Plus'],['premium','Premium']],sales=data.sales?.monthly||[],period=$('admin-sales-period').value;
  const now=parisDate(new Date().toISOString()).slice(0,7),end=new Date(now+'-01T12:00:00Z');
  const first=period==='all'?(sales.map(x=>x.month).sort()[0]||now):new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()-Number(period)+1,1)).toISOString().slice(0,7);
  const months=[];for(let d=new Date(first+'-01T12:00:00Z');d<=end;d.setUTCMonth(d.getUTCMonth()+1))months.push(d.toISOString().slice(0,7));
  const totals=period==='all'?(data.sales?.totals||[]):plans.map(([plan])=>({plan,purchases:sales.filter(x=>x.plan===plan&&x.month>=first&&x.month<=now).reduce((n,x)=>n+Number(x.purchases||0),0)}));
  $('admin-sales-totals').innerHTML=plans.map(([plan,label])=>{const n=totals.find(x=>x.plan===plan);return `<div><span>${label}</span><strong>${Number(n?.purchases||0)}</strong><span>achat(s) confirmé(s)</span></div>`;}).join('');
  const count=(month,plan)=>Number(sales.find(x=>x.month===month&&x.plan===plan)?.purchases||0),max=Math.max(1,...months.flatMap(m=>plans.map(([p])=>count(m,p))));
  const label=m=>new Date(m+'-01T12:00:00Z').toLocaleDateString('fr-FR',{month:'short',year:'2-digit'});
  const range=$('admin-sales-period').selectedOptions[0].textContent,total=totals.reduce((n,x)=>n+Number(x.purchases),0);
  $('admin-sales-description').textContent='Achats confirmés · '+range+'.';
  $('admin-sales-chart').innerHTML=(total?'':'<p class="hint">Aucune offre achetée sur cette période.</p>')+`<div class="admin-sales-scroll"><div class="admin-sales-bars" style="grid-template-columns:repeat(${months.length},minmax(48px,1fr));min-width:${Math.max(0,months.length*58)}px" role="img" aria-label="Nombre d’offres achetées par mois · ${esc(range)}. ${plans.map(([p,name])=>name+' : '+Number(totals.find(x=>x.plan===p)?.purchases||0)).join(', ')}">${months.map(m=>`<div class="admin-sales-month"><div class="admin-sales-group">${plans.map(([p,name])=>`<div class="admin-sales-bar" data-plan="${p}" style="height:${count(m,p)/max*100}%" title="${esc(label(m))} · ${name} : ${count(m,p)}"></div>`).join('')}</div><span>${esc(label(m))}</span></div>`).join('')}</div></div><div class="admin-sales-legend">${plans.map(([p,name])=>`<span><i data-plan="${p}" aria-hidden="true"></i>${name}</span>`).join('')}</div>`;
 }
 async function refreshServices(){try{const service=await api('services');$('offer-services').innerHTML=`<label class="admin-payment-toggle"><input id="admin-payments-toggle" type="checkbox" ${service.payments_enabled?'checked':''} ${service.configured.payments?'':'disabled data-locked="true"'}> Activer les achats de capsules</label>${service.configured.payments?'':'<p class="hint">Le service de paiement reste à configurer.</p>'}`;$('admin-payments-toggle').onchange=()=>run(async()=>{await api('configure_services',{payments_enabled:$('admin-payments-toggle').checked});});}catch{$('offer-services').textContent='Service de paiement momentanément indisponible.';}}
 function scheduleRefresh(){
  clearTimeout(timer);if(!authorized)return;timer=setTimeout(async()=>{if(!authorized)return;if(busy||document.activeElement?.matches('#capsule-cards input,#capsule-cards select')||!isActive()||document.visibilityState!=='visible'){scheduleRefresh();return}try{await refresh()}catch(e){status('Actualisation momentanément indisponible. Une nouvelle tentative suivra.',true);scheduleRefresh()}},15000);
 }
 async function refresh(){if(!authorized)return;data=await api('overview');if(!authorized)return;render();await refreshServices();if(busy)setBusy(true);scheduleRefresh();}


 function parisDate(value,last=false){if(!value)return '';const day=new Date(new Date(value).getTime()-(last?1000:0));return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(day);}
 function monthAfter(value,months){const d=new Date(value+'T12:00:00Z'),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+months);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10);}
 function capsuleBackup(id){return data.backups.filter(b=>b.scope_id===id).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))[0];}
 function renderBackups(){
  const scopes=new Map(data.capsules.map(c=>[c.id,c.name]));for(const b of data.backups)if(b.scope_id&&!scopes.has(b.scope_id))scopes.set(b.scope_id,b.label);
  if(backupScope!=='all'&&backupScope!=='global'&&!scopes.has(backupScope))backupScope='all';
  $('admin-backup-scope').innerHTML='<option value="all">Toutes les sauvegardes</option><option value="global">Toutes les capsules ensemble</option>'+[...scopes].map(([id,name])=>'<option value="'+esc(id)+'">'+esc(name)+'</option>').join('');$('admin-backup-scope').value=backupScope;
  const jobs=data.backups.filter(b=>backupScope==='all'||backupScope==='global'&&!b.scope_id||b.scope_id===backupScope);
  $('backup-cards').innerHTML=jobs.map(b=>{const expiry=new Date(Math.min(Date.parse(b.created_at)+7*86400000,b.expires_at?Date.parse(b.expires_at):Infinity)).toISOString();return `<article class="admin-card admin-backup"><div><strong>${esc(b.label)}</strong><p>${date(b.created_at)} · ${b.automatic?'Automatique':'Manuelle'} · ${esc(backupStates[b.state]||'Indisponible')}${['running','restoring'].includes(b.state)?' · '+(b.state==='restoring'?b.restore_cursor:b.cursor)+' / '+b.total+' fichiers':''}</p><small>Disponible jusqu’au ${date(expiry)}</small>${b.error?'<p class="admin-error">'+esc(b.error)+'</p>':''}</div><div class="admin-actions">${['ready','restored'].includes(b.state)?`<button type="button" class="btn secondary" data-export="${b.id}">Télécharger</button><button type="button" class="btn secondary" data-restore="${b.id}">Restaurer</button>`:b.state==='failed'?`<button type="button" class="btn secondary" data-retry="${b.id}">Réessayer</button>`:''}</div></article>`;}).join('')||'<p class="admin-empty">Aucune sauvegarde disponible pour cette sélection.</p>';
  const locked=!data.capsules.some(c=>c.usage.state!=='expired')||data.backups.some(b=>!b.scope_id&&['queued','running','restoring'].includes(b.state));$('backup-all').dataset.locked=String(locked);$('backup-all').disabled=busy||locked;
 }
 async function downloadCapsule(id){if(busy||!authorized)return;const c=data.capsules.find(x=>x.id===id);if(!c)return;await exportArchive(null,id);}
 async function exportArchive(id,capsuleId=null){
  const name='la-suite-'+new Date().toISOString().slice(0,10)+'.lasuite';let writable,parts=[],size=0,handle;
  // The file picker must run within the click gesture before any network request.
  if(window.showSaveFilePicker){handle=await window.showSaveFilePicker({suggestedName:name,types:[{description:'Archive La Suite',accept:{'application/octet-stream':['.lasuite']}}]});writable=await handle.createWritable();}
  else writable={write:async part=>{size+=part.size||part.byteLength;if(size>150000000)throw Error('Cette archive est volumineuse. Téléchargez-la depuis Chrome ou Edge sur ordinateur.');parts.push(part);},close:async()=>{const url=URL.createObjectURL(new Blob(parts,{type:'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},abort:async()=>{parts=[];}};
  try{if(capsuleId){setBusy(true);const previous=capsuleBackup(capsuleId);const started=previous&&['queued','running'].includes(previous.state)?previous:await api('backup',{id:capsuleId});id=started.id;if(!id)throw Error('La sauvegarde n’a pas pu être lancée.');let ready=false;for(let attempt=0;attempt<150;attempt++){if(downloadSession.signal.aborted)throw downloadSession.signal.reason;await api('tick');const snapshot=await api('overview'),job=snapshot.backups.find(b=>b.id===id);if(!job||job.state==='failed')throw Error(job?.error||'Sauvegarde indisponible.');if(['ready','restored'].includes(job.state)){ready=true;break}status('Préparation du téléchargement… '+Number(job.cursor||0)+' / '+Number(job.total||0)+' fichiers');await new Promise(r=>setTimeout(r,2000));}if(!ready)throw Error('La préparation continue en arrière-plan. Réessayez le téléchargement dans quelques instants.');}await SuiteArchive.write(offset=>api('export',{id,offset}),writable,(i,total)=>status('Téléchargement : '+i+' / '+total+' fichiers…'),{signal:downloadSession.signal});status('');}catch(e){await writable.abort?.();throw e;}finally{if(capsuleId){setBusy(false);if(authorized)await refresh();}}
 }
 async function importArchive(file){const entries=await SuiteArchive.entries(file),first=entries[0];if(!first||!first.name.endsWith('/manifest'))throw Error('Archive invalide.');if(!await confirmAction('Restaurer cette archive ?','Les éléments manquants seront remis en place. Les nouvelles contributions et les réglages existants seront conservés.'))return;
  await run(async()=>{const bytes=new Uint8Array(await first.blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const job=await api('import_start',{name:first.name,manifest:btoa(binary)});const byName=new Map(entries.slice(1).map(e=>[e.name,e.blob]));if(entries.length!==job.files.length+1)throw Error('Archive incomplète.');
   for(let i=0;i<job.files.length;i++){const f=job.files[i],blob=byName.get(f.key);if(!blob||blob.size!==f.size+28)throw Error('Archive incomplète.');const target=await api('import_url',{id:job.id,index:i});const {error}=await sb.storage.from('capsule-backups').uploadToSignedUrl(target.path,target.token,blob,{contentType:'application/octet-stream'});if(error)throw error;status('Import : '+(i+1)+' / '+job.files.length+' fichiers…');}
   await api('import_finish',{id:job.id});status('Restauration lancée. Elle continue même si vous fermez la page.');await api('tick');
  });
 }
 if($('refresh'))$('refresh').onclick=()=>run(async()=>{status('Liste actualisée.');});
 $('backup-all').onclick=()=>run(async()=>{await api('backup');status('Sauvegarde lancée. Elle continue en arrière-plan.');await api('tick');});
 $('import-backup').onclick=()=>{$('archive-input').value='';$('archive-input').click();};$('archive-input').onchange=async()=>{if($('archive-input').files[0])try{await importArchive($('archive-input').files[0]);}catch(e){status(e.message,true);}};
 const handleAdminClick=async e=>{const b=e.target.closest('button');if(!b||b.disabled||busy)return;
  if(b.dataset.attention){stateFilter='attention';renderCapsules();selectView('capsules');}
  if(b.dataset.sort){if(sortKey===b.dataset.sort)sortDirection*=-1;else{sortKey=b.dataset.sort;sortDirection=1;}renderCapsules();}
  if(b.dataset.capsuleDownload)try{await downloadCapsule(b.dataset.capsuleDownload)}catch(error){if(error.name!=='AbortError')status(error.message,true)}
  if(b.dataset.capsuleDelete){const c=data.capsules.find(x=>x.id===b.dataset.capsuleDelete);if(c&&await confirmAction('Supprimer cette capsule ?',c.name+' : les souvenirs et la capsule seront supprimés. Le compte client et les achats restent conservés. Les anciennes archives restent disponibles dans Paramètres.'))await run(async()=>{await api('delete_capsule',{id:c.id,expected_name:c.name});rowDrafts.delete(c.id);status('');});}
  if(b.dataset.export)run(()=>exportArchive(b.dataset.export));
  if(b.dataset.restore&&await confirmAction('Restaurer les éléments manquants ?','Les nouveaux souvenirs et les réglages actuels seront conservés.'))run(async()=>{await api('restore',{id:b.dataset.restore});await api('tick');});
  if(b.dataset.retry)run(async()=>{await api('retry',{id:b.dataset.retry});await api('tick');});
 };
 $('admin-content').onclick=handleAdminClick;
 document.querySelectorAll('[data-admin-view]').forEach(b=>b.onclick=()=>selectView(b.dataset.adminView));
 $('admin-backup-scope').onchange=()=>{backupScope=$('admin-backup-scope').value;renderBackups();};
 const captureRow=row=>{const id=row.dataset.capsuleRow,c=data.capsules.find(x=>x.id===id),old=rowDrafts.get(id);if(!c)return;const values={...(old?.values||rowValues(c)),...Object.fromEntries([...row.querySelectorAll('[data-field]')].map(e=>[e.dataset.field,e.type==='checkbox'?(e.checked?'yes':'no'):e.value]))};const draft=old||{expected:capsuleExpected(c),original:rowValues(c),capsule:{...c,usage:{...c.usage}}};draft.values=values;draft.error='';rowDrafts.set(id,draft);return draft;};
 $('capsule-cards').addEventListener('input',e=>{if(e.target.id==='admin-email-filter'){emailFilter=e.target.value.trim().toLocaleLowerCase('fr');const cursor=e.target.selectionStart;renderCapsules();$('admin-email-filter').focus();$('admin-email-filter').setSelectionRange(cursor,cursor);return;}const row=e.target.closest('[data-capsule-row]');if(row&&e.target.matches('[data-field]'))captureRow(row);});
 $('capsule-cards').addEventListener('change',async e=>{
  if(e.target.id==='admin-state-filter'){stateFilter=e.target.value;renderCapsules();return;}
  const row=e.target.closest('[data-capsule-row]');if(!row||!e.target.matches('[data-field]')||busy||!authorized)return;
  const draft=captureRow(row),c=draft.capsule,v=draft.values,old=draft.original,id=c.id;
  if(v.plan!=='custom'){v.base=v.plan;v.quota=String(planDefaults[v.plan].quota);v.deposit='2';v.storage='3';}
  const invalid=[...row.querySelectorAll('[data-field]')].find(input=>!input.disabled&&!input.checkValidity());if(invalid){invalid.reportValidity();draft.error='Corrigez le champ indiqué.';row.querySelector('.admin-row-status').textContent=draft.error;return;}
  if(v.email!==old.email){if(!await confirmAction('Changer l’adresse du client ?',old.email+' → '+v.email+'. Cette adresse deviendra son identifiant pour toutes ses capsules.')){rowDrafts.delete(id);renderCapsules();return;}setBusy(true);try{await api('client_email',{id,email:v.email,expected_email:old.email});rowDrafts.delete(id);status('');await refresh();}catch(error){draft.error=error.message;renderCapsules();}finally{setBusy(false);}return;}
  const payload={id,expected:draft.expected,mode:v.plan==='custom'?'custom':'standard',plan:v.plan==='custom'?v.base:v.plan};
  if(v.event!==old.event)payload.event_date=v.event;
  if(c.status==='active'&&v.activation!==old.activation)payload.activation_date=v.activation;
  if(v.paused!==old.paused)payload.suspended=v.paused==='yes';
  if(v.plan==='custom'){payload.quota=Math.round(Number(v.quota)*1e9);if(v.deposit!==old.deposit||v.storage!==old.storage||v.event!==old.event){const u=c.usage,open=v.event!==old.event?v.event:parisDate(u.opens_at);payload.rules={opens_on:open,closes_on:addDays(open,Number(v.deposit)-1),delivery_until:parisDate(u.delivery_before,true),access_until:v.storage!==old.storage||v.event!==old.event?monthAfter(v.event,Math.round(Number(v.storage)*12)):u.access_until||parisDate(u.expires_at,true)};if(v.storage!==old.storage)payload.rules.delivery_until=payload.rules.access_until;if(payload.rules.delivery_until>payload.rules.access_until)payload.rules.delivery_until=payload.rules.access_until;}}
  setBusy(true);row.querySelector('.admin-row-status').textContent='Enregistrement…';try{await api('manage',payload);if(!authorized)return;rowDrafts.delete(id);status('');await refresh();}catch(error){if(authorized){draft.error=error.message||'Enregistrement impossible.';renderCapsules();}}finally{setBusy(false);}
 });
 const accountReport=(id,text,error=false)=>{const el=$(id);el.textContent=text;el.className='status show '+(error?'err':'ok');};
 $('admin-email-form').onsubmit=async e=>{e.preventDefault();if(busy||!authorized||!e.target.reportValidity())return;const email=$('admin-new-email').value.trim();if(email.toLowerCase()===currentEmail.toLowerCase())return accountReport('admin-email-status','Cette adresse est déjà utilisée.');setBusy(true);try{const {error}=await sb.auth.updateUser({email},{emailRedirectTo:new URL('admin.html',location.href).href});if(error)throw error;if(authorized)accountReport('admin-email-status','Demande envoyée. Confirmez le changement via les e-mails reçus.');}catch(error){if(authorized)accountReport('admin-email-status',error.message||'Changement impossible.',true);}finally{setBusy(false);}};
 $('admin-password-form').onsubmit=async e=>{e.preventDefault();if(busy||!authorized||!e.target.reportValidity())return;const old=$('admin-current-password').value,password=$('admin-new-password').value;if(password!==$('admin-confirm-password').value)return accountReport('admin-password-status','Les nouveaux mots de passe ne correspondent pas.',true);if(password===old)return accountReport('admin-password-status','Choisissez un mot de passe différent de l’actuel.',true);setBusy(true);try{const checked=await sb.auth.signInWithPassword({email:currentEmail,password:old});if(checked.error)throw Error('Le mot de passe actuel est incorrect.');if(checked.data?.user&&checked.data.user.id!==sessionOwner)throw Error('Le compte a changé. Reconnectez-vous.');if(!authorized)return;const {error}=await sb.auth.updateUser({password});if(error)throw error;if(authorized){e.target.reset();accountReport('admin-password-status','Votre mot de passe a été modifié.');}}catch(error){if(authorized)accountReport('admin-password-status',error.message||'Modification impossible.',true);}finally{setBusy(false);}};

 $('admin-sales-period').onchange=renderSales;
 if($('admin-logout'))$('admin-logout').onclick=async()=>{if(busy){status('Patientez jusqu’à la fin de l’opération.',true);return;}clearPrivateView();await sb.auth.signOut();location.href='auth.html?next=admin';};
 try{const {data:user,error}=await sb.auth.getUser();if(error||!user.user){$('access-message').textContent=invite?'Connectez-vous ou créez votre compte pour activer votre accès administrateur.':'Connectez-vous avec votre compte administrateur.';$('admin-auth').hidden=false;$('admin-signup').hidden=!invite;if(!invite)location.replace('auth.html?next=admin');return;}
  const {data:member,error:memberError}=await sb.rpc('admin_status');if(memberError)throw memberError;if(member!==true){if(embedded){clearPrivateView();return;}if(!invite){$('access-message').textContent='Ce compte ne dispose pas d’un accès administrateur.';if($('admin-logout'))$('admin-logout').hidden=false;return;}const {error}=await sb.rpc('admin_claim',{p_token:invite.token});if(error)throw error;}
  if(downloadSession.signal.aborted)return;try{localStorage.removeItem(inviteKey)}catch{}sessionOwner=user.user.id;currentEmail=user.user.email||'';authorized=true;$('admin-account-email').textContent=currentEmail;if($('admin-logout'))$('admin-logout').hidden=false;$('admin-access').hidden=true;$('admin-content').hidden=false;await refresh();selectView('overview');const capsuleId=new URLSearchParams(location.search).get('capsule');if(capsuleId){selectView('capsules');[...document.querySelectorAll('[data-capsule-row]')].find(r=>r.dataset.capsuleRow===capsuleId)?.scrollIntoView();}
 }catch(e){$('access-message').textContent=e.message||'Vérification impossible. Rechargez la page.';status(e.message,true);}
 return {async configureCapsule(id){if(!authorized||busy)throw Error('Veuillez réessayer dans quelques instants.');await refresh();if(!authorized)return;selectView('capsules');[...document.querySelectorAll('[data-capsule-row]')].find(r=>r.dataset.capsuleRow===id)?.scrollIntoView();},exportCapsule(id){if(!authorized||busy)throw Error('Veuillez réessayer dans quelques instants.');if(!data.capsules.some(c=>c.id===id))throw Error('Capsule introuvable.');return downloadCapsule(id);}};
};
if(document.getElementById('admin-access'))window.initSuiteAdmin();



