'use strict';
window.initSuiteAdmin=async function({client,embedded=false,ownedCaps=[],isActive=()=>true,onBusy=()=>{},onDenied=()=>{}}={}){
 const $=id=>document.getElementById(id),cfg=window.LA_SUITE_CONFIG||{};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=v=>v?new Date(v.length===10?v+'T12:00:00':v).toLocaleDateString('fr-FR'):'—';const bytes=v=>Number(v)>=1e9?(Number(v)/1e9).toFixed(1)+' Go':Math.round(Number(v)/1e6)+' Mo';
 const states={draft:'En préparation',scheduled:'Prête à partager',open:'Dépôts ouverts',closed:'Dépôts terminés',full:'Stockage rempli',expired:'Conservation terminée',suspended:'Dépôts en pause',missing_date:'Date à compléter'};
 const backupStates={queued:'En attente',running:'Sauvegarde en cours',ready:'Sauvegarde prête',failed:'À réessayer',restoring:'Restauration en cours',restored:'Restaurée',importing:'Import en cours'};
 let backupScope='all',view='overview',rowDrafts=new Map(),sortDirection=1;
 let data={capsules:[],clients:[],backups:[]},busy=false,authorized=false,timer=null;
 function status(text,error=false){$('admin-status').textContent=text;$('admin-status').className='status show '+(error?'err':'ok');}
 function setBusy(value){busy=value;onBusy(value);document.querySelectorAll('#admin-content button:not([data-tab]),#capsule-dialog button:not(.dialog-close),#quota-form input,#quota-form select,#admin-content input,#admin-content select').forEach(b=>b.disabled=value||b.dataset.locked==='true');}
 window.addEventListener('hashchange',()=>{if(/^[a-f0-9]{64}$/.test(new URLSearchParams(location.hash.slice(1)).get('invite')||''))location.reload();});
 const inviteKey='la_suite_admin_invite';const hash=new URLSearchParams(location.hash.slice(1));let invite=null;if(/^[a-f0-9]{64}$/.test(hash.get('invite')||'')){invite={token:hash.get('invite'),at:Date.now()};try{localStorage.setItem(inviteKey,JSON.stringify(invite));history.replaceState(null,'',location.pathname)}catch{}}
 try{invite=invite||JSON.parse(localStorage.getItem(inviteKey)||'null');if(invite&&Date.now()-invite.at>48*3600000){localStorage.removeItem(inviteKey);invite=null;}}catch{}
 if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY||!window.supabase){$('access-message').textContent='Service indisponible. Rechargez la page.';return;}
 const sb=client||window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
 let sessionOwner=null,currentEmail='';
 const downloadSession=new AbortController();
 function clearPrivateView(){authorized=false;rowDrafts.clear();$('admin-email-form').reset();$('admin-password-form').reset();downloadSession.abort(new Error('Votre session est terminée. Reconnectez-vous.'));onBusy(false);clearTimeout(timer);data={capsules:[],clients:[],backups:[]};['capsule-cards','backup-cards','admin-stats','capsule-detail','admin-account-email','offer-services','admin-sales-totals','admin-sales-chart','admin-backup-scope'].forEach(id=>$(id)?.replaceChildren());$('admin-content').hidden=true;$('admin-access').hidden=false;$('access-message').textContent='Votre session est terminée. Reconnectez-vous.';$('admin-auth').hidden=false;$('admin-signup').hidden=true;if($('capsule-dialog').open)$('capsule-dialog').close();if($('confirm-dialog').open)$('confirm-dialog').dispatchEvent(new Event('cancel',{cancelable:true}));if(embedded)onDenied();}
 sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||sessionOwner&&session?.user?.id&&session.user.id!==sessionOwner)clearPrivateView();else if(event==='USER_UPDATED'&&session?.user?.email){currentEmail=session.user.email;$('admin-account-email').textContent=currentEmail;}});
 async function api(action,payload={}){if(downloadSession.signal.aborted)throw downloadSession.signal.reason;const {data,error}=await sb.functions.invoke('suite-admin',{body:{action,...payload}});if(downloadSession.signal.aborted)throw downloadSession.signal.reason;if(error){if([401,403].includes(error.context?.status))clearPrivateView();let message=error.message;try{message=(await error.context.json()).error||message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
 async function confirmAction(title,text){$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm-dialog').showModal();return new Promise(resolve=>{function done(value){$('confirm-dialog').close();$('confirm-yes').onclick=null;$('confirm-no').onclick=null;$('confirm-dialog').oncancel=null;resolve(value);}$('confirm-yes').onclick=()=>done(true);$('confirm-no').onclick=()=>done(false);$('confirm-dialog').oncancel=()=>done(false);});}
 async function run(fn){if(busy||!authorized)return;setBusy(true);try{await fn();await refresh();}catch(e){status(e.message||'Opération impossible.',true);}finally{setBusy(false);}}
 function attention(c){return ['full','suspended','missing_date'].includes(c.usage.state)||c.usage.used_bytes>=c.usage.quota_bytes*.8;}
 function email(id){return data.clients.find(x=>x.id===id)?.email||'Compte indisponible';}
 function render(){
  $('admin-stats').innerHTML=[['Capsules',data.capsules.length],['Clients',data.clients.filter(c=>!c.is_admin).length],['Capsules à surveiller',data.capsules.filter(attention).length],['Mo utilisés',(data.capsules.reduce((n,c)=>n+Number(c.usage.used_bytes),0)/1e6).toLocaleString('fr-FR',{maximumFractionDigits:1})]].map(([name,value])=>`<div class="admin-stat"><strong>${esc(value)}</strong><span>${name}</span>${name==='Capsules à surveiller'?'<small>Stockage ≥ 80 %, dépôts en pause ou date manquante.</small><button type="button" class="admin-text-button" data-attention="true">Voir les capsules</button>':''}</div>`).join('');
  renderCapsules();renderSales();renderBackups();

 }
 function selectView(next){
  if(!authorized||busy||!['overview','capsules','settings'].includes(next))return;
  view=next;document.querySelectorAll('[data-admin-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.adminView===view)));
  for(const key of ['overview','capsules','settings'])$('panel-'+key).hidden=key!==view;
 }
 function capsuleExpected(c){const u=c.usage;return {date:c.date,plan:c.plan,admin_plan_override:c.admin_plan_override??null,activated_at:c.activated_at??null,...Object.fromEntries(['opens_at','closes_at','delivery_before','expires_at','quota_bytes'].map(k=>[k,u[k]]))};}
 function dayCount(a,b){return Math.max(1,Math.round((new Date(b+'T12:00:00Z')-new Date(a+'T12:00:00Z'))/86400000)+1);}
 function addDays(a,n){const d=new Date(a+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
 function rowValues(c){const u=c.usage,open=parisDate(u.opens_at),close=parisDate(u.closes_at,true),end=u.access_until||parisDate(u.expires_at,true);return {plan:u.effective_plan||c.plan,activation:parisDate(c.activated_at),deposit:String(dayCount(open,close)),quota:String(u.quota_bytes/1e9),storage:String(Math.max(.1,Math.round((new Date(end+'T12:00:00Z')-new Date(c.date+'T12:00:00Z'))/86400000/365.25*10)/10))};}
 function renderCapsules(){
  const term=$('admin-capsule-search').value.trim().toLocaleLowerCase('fr'),sort=$('admin-sort').value,filter=$('admin-state-filter').value;
  const caps=data.capsules.filter(c=>(filter==='all'||filter==='attention'&&attention(c)||c.usage.state===filter)&&((c.name||'')+' '+email(c.owner_id)).toLocaleLowerCase('fr').includes(term)).sort((a,b)=>{const x=sort==='email'?email(a.owner_id):a[sort]||'',y=sort==='email'?email(b.owner_id):b[sort]||'';return sortDirection*(String(x).localeCompare(String(y),'fr',{numeric:true,sensitivity:'base'})||a.id.localeCompare(b.id));});
  const head=(key,label)=>`<th scope="col" ${key?'aria-sort="'+(sort===key?(sortDirection===1?'ascending':'descending'):'none')+'"':''}>${key?'<button type="button" data-sort="'+key+'">'+label+'</button>':label}</th>`;
  const rows=caps.map(c=>{const draft=rowDrafts.get(c.id),v=draft?.values||rowValues(c),form='admin-row-'+c.id,u=c.usage,job=capsuleBackup(c.id),pending=job&&['queued','running','restoring','importing'].includes(job.state),ready=job&&['ready','restored'].includes(job.state);
   const input=(key,type,extra='')=>`<input data-field="${key}" name="${key}" form="${form}" type="${type}" value="${esc(v[key])}" aria-label="${({activation:'Date d’activation',deposit:'Durée de dépôt en jours',quota:'Capacité en Go',storage:'Durée de stockage en années'})[key]} · ${esc(c.name)}" ${extra}>`;
   return `<tr data-capsule-row="${c.id}" data-previous-plan="${esc(v.plan)}"><td><strong>${esc(c.name)}</strong><small>Événement : ${date(c.date)}</small><span class="workspace-state" data-state="${esc(u.state)}">${esc(states[u.state]||'Indisponible')}</span></td><td>${esc(email(c.owner_id))}</td><td><select data-field="plan" name="plan" form="${form}" aria-label="Formule · ${esc(c.name)}">${[['photo','Essentiel'],['audio','Plus'],['premium','Premium']].map(([key,label])=>'<option value="'+key+'" '+(v.plan===key?'selected':'')+'>'+label+'</option>').join('')}</select></td><td>${input('activation','date',c.status==='active'?'required max="'+parisDate(new Date().toISOString())+'"':'disabled data-locked="true"')}<small>${c.status==='active'?'':'Pas encore activée'}</small></td><td>${input('deposit','number','required min="1" max="36525" step="1"')} jours<small>À partir du ${date(parisDate(u.opens_at))}</small></td><td>${input('quota','number','required min="'+Math.max(.1,Math.ceil(Number(u.used_bytes)/1e8)/10)+'" max="50" step="0.1"')} Go<small>${bytes(u.used_bytes)} utilisés</small></td><td>${input('storage','number','required min="0.1" max="100" step="0.1"')} ans<small>Jusqu’au ${date(u.access_until||parisDate(u.expires_at,true))}</small></td><td><form id="${form}" data-capsule-save="${c.id}" class="admin-row-actions"><button type="submit" class="btn primary">Enregistrer</button><button type="button" class="btn secondary" data-capsule-open="${c.id}">Détails</button><button type="button" class="btn secondary" data-capsule-reset="${c.id}" ${draft?'':'hidden'}>Annuler les modifications</button><p class="admin-row-status" role="status">${esc(draft?.error||'')}</p></form></td><td><div class="admin-row-backups"><button type="button" class="btn secondary" data-capsule-backup="${c.id}" ${pending||u.state==='expired'?'disabled data-locked="true"':''}>${pending?'En cours…':'Sauvegarder'}</button>${ready?'<button type="button" class="btn secondary" data-export="'+job.id+'">Télécharger</button>':''}${job?'<button type="button" class="admin-text-button" data-backup-scope="'+c.id+'">Voir les archives</button><small role="status">'+esc(backupStates[job.state]||'Indisponible')+' · '+date(job.created_at)+'</small>':'<small>'+(u.state==='expired'?'Conservation terminée':'Aucune sauvegarde individuelle')+'</small>'}${job?.error?'<small class="admin-error">'+esc(job.error)+'</small>':''}</div></td></tr>`;});
  $('capsule-cards').innerHTML=caps.length?`<table class="admin-capsules-table"><caption class="sr-only">Capsules et réglages</caption><thead><tr>${head('name','Nom')}${head('email','E-mail')}${head(null,'Formule')}${head('activated_at','Activation')}${head(null,'Durée de dépôt')}${head(null,'Taille de dépôt')}${head(null,'Durée de stockage')}${head(null,'Réglages')}${head(null,'Sauvegarde')}</tr></thead><tbody>${rows.join('')}</tbody></table>`:'<p class="admin-empty">Aucune capsule à afficher.</p>';
 }
 function renderSales(){
  const plans=[['photo','Essentiel'],['audio','Plus'],['premium','Premium']],sales=data.sales?.monthly||[],period=$('admin-sales-period').value;
  const now=parisDate(new Date().toISOString()).slice(0,7),end=new Date(now+'-01T12:00:00Z');
  const first=period==='all'?(sales.map(x=>x.month).sort()[0]||now):new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()-Number(period)+1,1)).toISOString().slice(0,7);
  const months=[];for(let d=new Date(first+'-01T12:00:00Z');d<=end;d.setUTCMonth(d.getUTCMonth()+1))months.push(d.toISOString().slice(0,7));
  const totals=period==='all'?(data.sales?.totals||[]):plans.map(([plan])=>({plan,purchases:sales.filter(x=>x.plan===plan&&x.month>=first&&x.month<=now).reduce((n,x)=>n+Number(x.purchases||0),0)}));
  $('admin-sales-totals').innerHTML=plans.map(([plan,label])=>{const n=totals.find(x=>x.plan===plan);return `<div><span>${label}</span><strong>${Number(n?.purchases||0)}</strong><span>achat(s) confirmé(s)</span></div>`;}).join('');
  const count=(month,plan)=>Number(sales.find(x=>x.month===month&&x.plan===plan)?.purchases||0),max=Math.max(1,...months.flatMap(m=>plans.map(([p])=>count(m,p))));
  const label=m=>new Date(m+'-01T12:00:00Z').toLocaleDateString('fr-FR',{month:'short',year:'2-digit'});
  const range=$('admin-sales-period').selectedOptions[0].textContent,total=totals.reduce((n,x)=>n+Number(x.purchases),0);
  $('admin-sales-description').textContent='Achats confirmés · '+range+'.';
  $('admin-sales-chart').innerHTML=(total?'':'<p class="hint">Aucune offre achetée sur cette période.</p>')+`<div class="admin-sales-scroll"><div class="admin-sales-bars" style="grid-template-columns:repeat(${months.length},minmax(48px,1fr));min-width:${Math.max(0,months.length*58)}px" role="img" aria-label="Nombre d’offres achetées par mois · ${esc(range)}. ${plans.map(([p,name])=>name+' : '+Number(totals.find(x=>x.plan===p)?.purchases||0)).join(', ')}">${months.map(m=>`<div class="admin-sales-month"><div class="admin-sales-group">${plans.map(([p,name])=>`<div class="admin-sales-bar" data-plan="${p}" style="height:${count(m,p)/max*100}%" title="${esc(label(m))} · ${name} : ${count(m,p)}"></div>`).join('')}</div><span>${esc(label(m))}</span></div>`).join('')}</div></div><div class="admin-sales-legend">${plans.map(([p,name])=>`<span><i data-plan="${p}" aria-hidden="true"></i>${name}</span>`).join('')}</div>`;
 }
 async function refreshServices(){
  try{const service=await api('services');$('offer-services').innerHTML=[['notifications','Notifications par e-mail',service.notifications_enabled,'Un récapitulatif des souvenirs ouverts par jour et deux rappels avant expiration.'],['payments','Achats de capsules',service.payments_enabled,'Paiement unique pour activer une nouvelle capsule. Les capsules déjà activées gratuitement conservent leurs droits.']].map(([key,label,enabled,note])=>'<p><strong>'+label+' : '+(enabled?'activés':service.configured[key]?'prêts à activer':'à configurer')+'</strong><br>'+note+'</p>'+(service.configured[key]?'<button type="button" class="btn secondary" data-service="'+key+'" data-enabled="'+enabled+'">'+(enabled?'Désactiver':'Activer')+'</button>':'')).join('')+'<p class="hint">'+Number(service.failed_notifications||0)+' notification(s) à vérifier · '+Number(service.refunds_to_check||0)+' remboursement(s) à vérifier.</p><p><a href="https://github.com/Orbivia/LA_SUITE_WEB/blob/main/SERVICE-SETUP.md" target="_blank" rel="noopener">Guide de configuration</a></p>';
   $('offer-services').querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>run(async()=>{const payload={[b.dataset.service+'_enabled']:b.dataset.enabled!=='true'};await api('configure_services',payload);await refreshServices();status('Réglage enregistré.');}));
  }catch(e){$('offer-services').textContent='Les services sont momentanément indisponibles. Actualisez la page.';}
 }
 function scheduleRefresh(){
  clearTimeout(timer);if(!authorized)return;timer=setTimeout(async()=>{if(!authorized)return;if(busy||document.activeElement?.matches('#capsule-cards input,#capsule-cards select')||$('capsule-dialog').open||!isActive()||document.visibilityState!=='visible'){scheduleRefresh();return}try{await refresh()}catch(e){status('Actualisation momentanément indisponible. Une nouvelle tentative suivra.',true);scheduleRefresh()}},15000);
 }
 async function refresh(){if(!authorized)return;data=await api('overview');if(!authorized)return;render();await refreshServices();if(busy)setBusy(true);scheduleRefresh();}


 function parisDate(value,last=false){if(!value)return '';const day=new Date(new Date(value).getTime()-(last?1000:0));return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(day);}
 function monthAfter(value,months){const d=new Date(value+'T12:00:00Z'),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+months);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10);}
 function detail(id,configure=false){
  const c=data.capsules.find(x=>x.id===id);if(!c)return;
  const u=c.usage,quota=(c.quota_override||u.quota_bytes)/1e9;
  const expiry=u.access_until||parisDate(u.expires_at,true),open=parisDate(u.opens_at),close=parisDate(u.closes_at,true),delivery=parisDate(u.delivery_before,true);
  const expected=capsuleExpected(c);
  $('capsule-detail').innerHTML=`<div class="eyebrow">Paramètres de la capsule</div><h2>${esc(c.name)}</h2><p>${esc(email(c.owner_id))} · ${date(c.date)}</p><dl class="admin-detail"><div><dt>Souvenirs reçus</dt><dd>${c.messages}</dd></div><div><dt>Stockage</dt><dd>${bytes(u.used_bytes)} / ${bytes(u.quota_bytes)}</dd></div><div><dt>Activation</dt><dd>${c.activation==='payment'?'Payante':c.activation?'Gratuite':'À activer'} · ${({photo:'Essentiel',audio:'Plus',premium:'Premium'})[u.effective_plan||c.plan]||'Premium'}</dd></div><div><dt>Conservation jusqu’au</dt><dd>${date(expiry)}</dd></div></dl>
   <section class="admin-quota">
    <form id="quota-form">
     <p class="hint">Dates incluses, à l’heure de Paris. Les dates choisies pour les souvenirs déjà reçus sont conservées.</p>
     <fieldset><legend>Événement et formule</legend><div class="admin-rules-grid">
      <div class="field"><label for="admin-event-date">Date de l’événement</label><input id="admin-event-date" type="date" required value="${esc(c.date)}"></div>
      <div class="field"><label for="admin-plan">Formule</label><select id="admin-plan"><option value="photo">Essentiel · photos et textes</option><option value="audio">Plus · photos, textes et audios</option><option value="premium">Premium · tous les formats</option></select></div>
     </div><small>Les souvenirs reçus sont conservés. La formule s’applique aux prochains dépôts.</small></fieldset>
     <fieldset><legend>Activation</legend><div class="field"><label for="admin-activation-date">Date d’activation</label><input id="admin-activation-date" type="date" max="${parisDate(new Date().toISOString())}" value="${esc(parisDate(c.activated_at))}" ${c.status==='active'?'required':'disabled data-locked="true"'}><small>${c.status==='active'?'La date de l’événement et celle du paiement restent conservées.':'Disponible après activation de la capsule.'}</small></div></fieldset><fieldset><legend>Période de dépôt</legend><div class="admin-rules-grid">
      <div class="field"><label for="admin-opens-on">Ouverture des dépôts</label><input id="admin-opens-on" type="date" required value="${esc(open)}"></div>
      <div class="field"><label for="admin-closes-on">Dernier jour de dépôt</label><input id="admin-closes-on" type="date" required value="${esc(close)}"></div>
     </div><div class="admin-date-presets" aria-label="Durée des dépôts"><button type="button" data-deposit-preset="2">J et J+1</button><button type="button" data-deposit-preset="month">1 mois</button><button type="button" data-deposit-preset="3months">3 mois</button></div></fieldset>
     <fieldset><legend>Durée de la capsule</legend><div class="field"><label for="admin-duration-years">Durée depuis l’événement</label><select id="admin-duration-years"><option value="custom">Dates personnalisées</option><option value="1">1 an</option><option value="3">3 ans</option><option value="5">5 ans</option><option value="10">10 ans</option></select><small>Choisir une durée renseigne la conservation et la dernière découverte possible.</small></div><div class="admin-rules-grid">
      <div class="field"><label for="admin-delivery-until">Dernière date de découverte possible</label><input id="admin-delivery-until" type="date" required value="${esc(delivery)}"><small>Limite proposée aux invités pour leurs prochains souvenirs.</small></div>
      <div class="field"><label for="admin-access-until">Dernier jour de conservation</label><input id="admin-access-until" type="date" required min="${parisDate(new Date().toISOString())}" value="${esc(expiry)}"><small>Les souvenirs restent consultables jusqu’à cette date incluse.</small></div>
     </div></fieldset>
     <fieldset><legend>Stockage</legend><div class="field"><label for="quota">Capacité totale (Go)</label><input id="quota" type="number" min="${Math.max(.1,Math.ceil(Number(u.used_bytes)/1e8)/10)}" max="50" step="0.1" required value="${quota}"><small>De 0,1 à 50 Go, au moins l’espace déjà utilisé.</small></div></fieldset>
     <p id="admin-rules-status" class="status" role="status" aria-live="polite"></p><button class="btn primary" type="submit">Enregistrer les réglages</button>
    </form>
   </section>
   <div class="admin-actions"><button id="detail-suspend" class="btn secondary">${c.suspended?'Reprendre les dépôts':'Mettre les dépôts en pause'}</button></div>`;
  $('detail-suspend').onclick=async()=>{if(!await confirmAction(c.suspended?'Reprendre les dépôts ?':'Mettre les dépôts en pause ?',c.suspended?'Les dates et les limites de cette capsule s’appliqueront.':'Les invités ne pourront plus déposer de souvenir. Les souvenirs existants sont conservés.'))return;await run(async()=>{await api('manage',{id,suspended:!c.suspended});$('capsule-dialog').close();window.dispatchEvent(new CustomEvent('suite-capsule-rules-changed',{detail:id}));status(c.suspended?'Les dépôts ont repris.':'Les dépôts sont en pause.');});};
  const planInput=$('admin-plan');planInput.value=u.effective_plan||c.plan;
  const defaults={photo:1,audio:2,premium:5};let previousPlan=planInput.value;
  planInput.onchange=()=>{if(Number($('quota').value)===defaults[previousPlan])$('quota').value=defaults[planInput.value];previousPlan=planInput.value;};
  $('admin-duration-years').onchange=()=>{const years=$('admin-duration-years').value,day=$('admin-event-date').value;if(years==='custom'||!day)return;const end=monthAfter(day,Number(years)*12);$('admin-access-until').value=end;$('admin-delivery-until').value=end;};
  $('admin-access-until').oninput=()=>{$('admin-duration-years').value='custom';};
  $('admin-event-date').onchange=()=>{if(u.custom_rules)return;const day=$('admin-event-date').value;if(!day)return;$('admin-opens-on').value=day;const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);$('admin-closes-on').value=d.toISOString().slice(0,10);$('admin-delivery-until').value=monthAfter(day,30);const end=new Date(monthAfter(day,36)+'T12:00:00Z');end.setUTCDate(end.getUTCDate()-1);$('admin-access-until').value=end.toISOString().slice(0,10);$('admin-duration-years').value='3';};
  $('quota-form').querySelectorAll('[data-deposit-preset]').forEach(b=>b.onclick=()=>{
   const day=$('admin-opens-on').value;if(!day)return;
   if(b.dataset.depositPreset==='2'){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);$('admin-closes-on').value=d.toISOString().slice(0,10);}
   else $('admin-closes-on').value=monthAfter(day,b.dataset.depositPreset==='month'?1:3);
   $('admin-closes-on').focus();
  });
  $('quota-form').onsubmit=async e=>{
   e.preventDefault();if(busy||!authorized||!e.target.reportValidity())return;
   const rules={opens_on:$('admin-opens-on').value,closes_on:$('admin-closes-on').value,delivery_until:$('admin-delivery-until').value,access_until:$('admin-access-until').value};
   const report=(text,error=false)=>{const el=$('admin-rules-status');if(!el)return;el.textContent=text;el.className='status show '+(error?'err':'ok');};
   if(rules.opens_on>rules.closes_on||rules.closes_on>rules.delivery_until||rules.delivery_until>rules.access_until){report('Respectez l’ordre : ouverture, fin des dépôts, dernière découverte, fin de conservation.',true);return;}
   setBusy(true);report('Enregistrement…');
   try{
    await api('manage',{id,event_date:$('admin-event-date').value,...(c.status==='active'?{activation_date:$('admin-activation-date').value}:{}),plan:planInput.value,quota:Math.round(Number($('quota').value)*1e9),rules,expected});
    if(!authorized)return;await refresh();if(!authorized)return;$('capsule-dialog').close();window.dispatchEvent(new CustomEvent('suite-capsule-rules-changed',{detail:id}));status('Réglages de la capsule enregistrés.');
   }catch(e){if(authorized)report(e.message||'Enregistrement impossible. Réessayez.',true);}
   finally{setBusy(false);}
  };
  if(!$('capsule-dialog').open)$('capsule-dialog').showModal();$('admin-event-date').focus();
 }
 function capsuleBackup(id){return data.backups.filter(b=>b.scope_id===id).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))[0];}
 function renderBackups(){
  const scopes=new Map(data.capsules.map(c=>[c.id,c.name]));for(const b of data.backups)if(b.scope_id&&!scopes.has(b.scope_id))scopes.set(b.scope_id,b.label);
  if(backupScope!=='all'&&backupScope!=='global'&&!scopes.has(backupScope))backupScope='all';
  $('admin-backup-scope').innerHTML='<option value="all">Toutes les sauvegardes</option><option value="global">Toutes les capsules ensemble</option>'+[...scopes].map(([id,name])=>'<option value="'+esc(id)+'">'+esc(name)+'</option>').join('');$('admin-backup-scope').value=backupScope;
  const jobs=data.backups.filter(b=>backupScope==='all'||backupScope==='global'&&!b.scope_id||b.scope_id===backupScope);
  $('backup-cards').innerHTML=jobs.map(b=>{const expiry=new Date(Math.min(Date.parse(b.created_at)+7*86400000,b.expires_at?Date.parse(b.expires_at):Infinity)).toISOString();return `<article class="admin-card admin-backup"><div><strong>${esc(b.label)}</strong><p>${date(b.created_at)} · ${b.automatic?'Automatique':'Manuelle'} · ${esc(backupStates[b.state]||'Indisponible')}${['running','restoring'].includes(b.state)?' · '+(b.state==='restoring'?b.restore_cursor:b.cursor)+' / '+b.total+' fichiers':''}</p><small>Disponible jusqu’au ${date(expiry)}</small>${b.error?'<p class="admin-error">'+esc(b.error)+'</p>':''}</div><div class="admin-actions">${['ready','restored'].includes(b.state)?`<button type="button" class="btn secondary" data-export="${b.id}">Télécharger</button><button type="button" class="btn secondary" data-restore="${b.id}">Restaurer</button>`:b.state==='failed'?`<button type="button" class="btn secondary" data-retry="${b.id}">Réessayer</button>`:''}</div></article>`;}).join('')||'<p class="admin-empty">Aucune sauvegarde disponible pour cette sélection.</p>';
  const locked=!data.capsules.some(c=>c.usage.state!=='expired')||data.backups.some(b=>!b.scope_id&&['queued','running','restoring'].includes(b.state));$('backup-all').dataset.locked=String(locked);$('backup-all').disabled=busy||locked;
 }
 async function backupCapsule(id){await run(async()=>{const c=data.capsules.find(c=>c.id===id);if(!c)return;const job=await api('backup',{id});if(!job?.id)throw Error('La sauvegarde n’a pas pu être lancée.');backupScope=id;status('Sauvegarde de '+c.name+' lancée.'+(rowDrafts.has(id)?' Les modifications non enregistrées ne sont pas incluses.':''));try{await api('tick');}catch{status('Sauvegarde enregistrée. Elle sera traitée en arrière-plan.');}});}
 async function exportArchive(id){
  const name='la-suite-'+new Date().toISOString().slice(0,10)+'.lasuite';let writable,parts=[],size=0,handle;
  // The file picker must run within the click gesture before any network request.
  if(window.showSaveFilePicker){handle=await window.showSaveFilePicker({suggestedName:name,types:[{description:'Archive La Suite',accept:{'application/octet-stream':['.lasuite']}}]});writable=await handle.createWritable();}
  else writable={write:async part=>{size+=part.size||part.byteLength;if(size>150000000)throw Error('Cette archive est volumineuse. Téléchargez-la depuis Chrome ou Edge sur ordinateur.');parts.push(part);},close:async()=>{const url=URL.createObjectURL(new Blob(parts,{type:'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},abort:async()=>{parts=[];}};
  try{await SuiteArchive.write(offset=>api('export',{id,offset}),writable,(i,total)=>status('Téléchargement : '+i+' / '+total+' fichiers…'),{signal:downloadSession.signal});status('Archive téléchargée. Gardez-la en lieu sûr.');}catch(e){await writable.abort?.();throw e;}
 }
 async function importArchive(file){const entries=await SuiteArchive.entries(file),first=entries[0];if(!first||!first.name.endsWith('/manifest'))throw Error('Archive invalide.');if(!await confirmAction('Restaurer cette archive ?','Les éléments manquants seront remis en place. Les nouvelles contributions et les réglages existants seront conservés.'))return;
  await run(async()=>{const bytes=new Uint8Array(await first.blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const job=await api('import_start',{name:first.name,manifest:btoa(binary)});const byName=new Map(entries.slice(1).map(e=>[e.name,e.blob]));if(entries.length!==job.files.length+1)throw Error('Archive incomplète.');
   for(let i=0;i<job.files.length;i++){const f=job.files[i],blob=byName.get(f.key);if(!blob||blob.size!==f.size+28)throw Error('Archive incomplète.');const target=await api('import_url',{id:job.id,index:i});const {error}=await sb.storage.from('capsule-backups').uploadToSignedUrl(target.path,target.token,blob,{contentType:'application/octet-stream'});if(error)throw error;status('Import : '+(i+1)+' / '+job.files.length+' fichiers…');}
   await api('import_finish',{id:job.id});status('Restauration lancée. Elle continue même si vous fermez la page.');await api('tick');
  });
 }
 if($('refresh'))$('refresh').onclick=()=>run(async()=>{status('Liste actualisée.');});
 $('backup-all').onclick=()=>run(async()=>{await api('backup');status('Sauvegarde lancée. Elle continue en arrière-plan.');await api('tick');});
 $('import-backup').onclick=()=>{$('archive-input').value='';$('archive-input').click();};$('archive-input').onchange=async()=>{if($('archive-input').files[0])try{await importArchive($('archive-input').files[0]);}catch(e){status(e.message,true);}};
 const handleAdminClick=async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.attention){$('admin-state-filter').value='attention';renderCapsules();selectView('capsules');}if(b.dataset.sort){if($('admin-sort').value===b.dataset.sort)sortDirection*=-1;else{$('admin-sort').value=b.dataset.sort;sortDirection=1;}updateSort();}if(b.dataset.capsuleBackup)await backupCapsule(b.dataset.capsuleBackup);if(b.dataset.backupScope){backupScope=b.dataset.backupScope;renderBackups();$('panel-backups').scrollIntoView({behavior:'smooth',block:'start'});}if(b.dataset.capsuleReset){rowDrafts.delete(b.dataset.capsuleReset);renderCapsules();}if(b.dataset.capsuleOpen)detail(b.dataset.capsuleOpen);if(b.dataset.export)run(()=>exportArchive(b.dataset.export));if(b.dataset.restore){if(await confirmAction('Restaurer les éléments manquants ?','Les nouveaux souvenirs et les réglages actuels seront conservés. Les dates de dévoilement de la sauvegarde restent respectées.'))run(async()=>{await api('restore',{id:b.dataset.restore});status('Restauration lancée.');await api('tick');});}if(b.dataset.retry)run(async()=>{await api('retry',{id:b.dataset.retry});status('Opération relancée.');await api('tick');});};
 $('admin-content').onclick=handleAdminClick;
 document.querySelectorAll('[data-admin-view]').forEach(b=>b.onclick=()=>{if(b.dataset.adminView==='capsules')renderCapsules();selectView(b.dataset.adminView);});

 function updateSort(){$('admin-sort-direction').textContent=sortDirection===1?'Croissant ↑':'Décroissant ↓';renderCapsules();}
 $('admin-backup-scope').onchange=()=>{backupScope=$('admin-backup-scope').value;renderBackups();};$('admin-state-filter').onchange=renderCapsules;
 $('admin-sort').onchange=()=>{sortDirection=1;updateSort();};$('admin-sort-direction').onclick=()=>{sortDirection*=-1;updateSort();};
 const captureRow=row=>{const id=row.dataset.capsuleRow,c=data.capsules.find(x=>x.id===id),old=rowDrafts.get(id);if(!c)return null;const values=Object.fromEntries([...row.querySelectorAll('[data-field]')].map(e=>[e.dataset.field,e.value]));const draft=old||{expected:capsuleExpected(c),original:rowValues(c),capsule:{...c,usage:{...c.usage}}};draft.values=values;draft.error='';rowDrafts.set(id,draft);row.querySelector('[data-capsule-reset]').hidden=false;return draft;};
 $('capsule-cards').addEventListener('input',e=>{const row=e.target.closest('[data-capsule-row]');if(row&&e.target.matches('[data-field]'))captureRow(row);});
 $('capsule-cards').addEventListener('change',e=>{const row=e.target.closest('[data-capsule-row]');if(row&&e.target.matches('[data-field]')){if(e.target.dataset.field==='plan'){const previous=row.dataset.previousPlan,quota=row.querySelector('[data-field=quota]'),defaults={photo:1,audio:2,premium:5};if(Number(quota.value)===defaults[previous])quota.value=defaults[e.target.value];row.dataset.previousPlan=e.target.value;}captureRow(row);}});
 $('capsule-cards').addEventListener('submit',async e=>{
  const form=e.target.closest('[data-capsule-save]');if(!form)return;e.preventDefault();if(busy||!authorized||!form.reportValidity())return;
  const row=form.closest('[data-capsule-row]'),draft=captureRow(row),c=draft.capsule,v=draft.values,old=draft.original,id=c.id;
  const payload={id,expected:draft.expected};if(v.plan!==old.plan)payload.plan=v.plan;if(v.quota!==old.quota)payload.quota=Math.round(Number(v.quota)*1e9);if(c.status==='active'&&v.activation!==old.activation)payload.activation_date=v.activation;
  if(v.deposit!==old.deposit||v.storage!==old.storage){const u=c.usage,rules={opens_on:parisDate(u.opens_at),closes_on:parisDate(u.closes_at,true),delivery_until:parisDate(u.delivery_before,true),access_until:u.access_until||parisDate(u.expires_at,true)};
   if(v.deposit!==old.deposit)rules.closes_on=addDays(rules.opens_on,Number(v.deposit)-1);
   if(v.storage!==old.storage){rules.access_until=monthAfter(c.date,Math.round(Number(v.storage)*12));rules.delivery_until=rules.access_until;}
   payload.rules=rules;
  }
  setBusy(true);try{await api('manage',payload);if(!authorized)return;rowDrafts.delete(id);await refresh();if(authorized)status('Réglages de '+c.name+' enregistrés.');}catch(error){if(authorized){draft.error=error.message||'Enregistrement impossible.';rowDrafts.set(id,draft);renderCapsules();status(draft.error,true);}}finally{setBusy(false);}
 });
 const accountReport=(id,text,error=false)=>{const el=$(id);el.textContent=text;el.className='status show '+(error?'err':'ok');};
 $('admin-email-form').onsubmit=async e=>{e.preventDefault();if(busy||!authorized||!e.target.reportValidity())return;const email=$('admin-new-email').value.trim();if(email.toLowerCase()===currentEmail.toLowerCase())return accountReport('admin-email-status','Cette adresse est déjà utilisée.');setBusy(true);try{const {error}=await sb.auth.updateUser({email},{emailRedirectTo:new URL('admin.html',location.href).href});if(error)throw error;if(authorized)accountReport('admin-email-status','Demande envoyée. Confirmez le changement via les e-mails reçus.');}catch(error){if(authorized)accountReport('admin-email-status',error.message||'Changement impossible.',true);}finally{setBusy(false);}};
 $('admin-password-form').onsubmit=async e=>{e.preventDefault();if(busy||!authorized||!e.target.reportValidity())return;const old=$('admin-current-password').value,password=$('admin-new-password').value;if(password!==$('admin-confirm-password').value)return accountReport('admin-password-status','Les nouveaux mots de passe ne correspondent pas.',true);if(password===old)return accountReport('admin-password-status','Choisissez un mot de passe différent de l’actuel.',true);setBusy(true);try{const checked=await sb.auth.signInWithPassword({email:currentEmail,password:old});if(checked.error)throw Error('Le mot de passe actuel est incorrect.');if(checked.data?.user&&checked.data.user.id!==sessionOwner)throw Error('Le compte a changé. Reconnectez-vous.');if(!authorized)return;const {error}=await sb.auth.updateUser({password});if(error)throw error;if(authorized){e.target.reset();accountReport('admin-password-status','Votre mot de passe a été modifié.');}}catch(error){if(authorized)accountReport('admin-password-status',error.message||'Modification impossible.',true);}finally{setBusy(false);}};

 $('admin-sales-period').onchange=renderSales;$('admin-capsule-search').oninput=renderCapsules;
 if($('admin-logout'))$('admin-logout').onclick=async()=>{if(busy){status('Patientez jusqu’à la fin de l’opération.',true);return;}clearPrivateView();await sb.auth.signOut();location.href='auth.html?next=admin';};
 try{const {data:user,error}=await sb.auth.getUser();if(error||!user.user){$('access-message').textContent=invite?'Connectez-vous ou créez votre compte pour activer votre accès administrateur.':'Connectez-vous avec votre compte administrateur.';$('admin-auth').hidden=false;$('admin-signup').hidden=!invite;if(!invite)location.replace('auth.html?next=admin');return;}
  const {data:member,error:memberError}=await sb.rpc('admin_status');if(memberError)throw memberError;if(member!==true){if(embedded){clearPrivateView();return;}if(!invite){$('access-message').textContent='Ce compte ne dispose pas d’un accès administrateur.';if($('admin-logout'))$('admin-logout').hidden=false;return;}const {error}=await sb.rpc('admin_claim',{p_token:invite.token});if(error)throw error;}
  if(downloadSession.signal.aborted)return;try{localStorage.removeItem(inviteKey)}catch{}sessionOwner=user.user.id;currentEmail=user.user.email||'';authorized=true;$('admin-account-email').textContent=currentEmail;if($('admin-logout'))$('admin-logout').hidden=false;$('admin-access').hidden=true;$('admin-content').hidden=false;await refresh();selectView('overview');const capsuleId=new URLSearchParams(location.search).get('capsule');if(capsuleId){selectView('capsules');detail(capsuleId);}
 }catch(e){$('access-message').textContent=e.message||'Vérification impossible. Rechargez la page.';status(e.message,true);}
 return {async configureCapsule(id){if(!authorized||busy)throw Error('Veuillez réessayer dans quelques instants.');await refresh();if(!authorized)return;detail(id,true);},exportCapsule(id){if(!authorized||busy)throw Error('Veuillez réessayer dans quelques instants.');if(!data.capsules.some(c=>c.id===id))throw Error('Capsule introuvable.');return backupCapsule(id);}};
};
if(document.getElementById('admin-access'))window.initSuiteAdmin();



