/* Compact organizer layout. Move existing controls, preserving persistence and validation. */
(function(){
 'use strict';
 window.SuiteOrganizerLayout={mount(c){
  const $=id=>document.getElementById(id),controls=document.querySelector('.qr-designer-controls');
  if(!controls||document.body.classList.contains('organizer-layout-ready'))return;
  document.body.classList.add('organizer-layout-ready');
  const header=document.querySelector('.suite-topbar'),tabs=document.querySelector('.owner-tabs');
  const brand=header.querySelector('.suite-brand img');brand.src='assets/la-suite-logo.webp?v=20261010-forge-type';brand.alt='La Suite — Capsule temporelle';
  header.insertBefore(tabs,header.children[1]);
  new ResizeObserver(()=>document.body.style.setProperty('--organizer-header-height',Math.ceil(header.parentElement.getBoundingClientRect().height)+'px')).observe(header.parentElement);
  const selector=document.querySelector('.workspace-selector');
  if(!selector){const choose=document.createElement('button');choose.type='button';choose.className='organizer-capsule-selector';choose.innerHTML='Mes capsules <i class="fa-solid fa-chevron-down" aria-hidden="true"></i>';choose.setAttribute('aria-haspopup','dialog');choose.setAttribute('aria-controls','workspace-capsules');choose.onclick=()=>$('workspace-open-capsules').click();header.insertBefore(choose,header.querySelector('.workspace-account-button'));}
  if(selector){selector.classList.add('organizer-capsule-selector');const label=document.createElement('span');label.textContent='Mes capsules';selector.prepend(label);header.insertBefore(selector,header.querySelector('.workspace-account-button'));}
  const head=document.querySelector('.qr-designer-head');const subtitle=document.createElement('p');subtitle.textContent='Créez une carte QR et une page d’accueil qui vous ressemblent.';head.firstElementChild.append(subtitle);
  const edit=document.createElement('button');edit.id='organizer-modify';edit.type='button';edit.className='btn secondary organizer-modify';edit.setAttribute('aria-controls','organizer-editor-controls');controls.id='organizer-editor-controls';head.append(edit);
  const mobileLayout=matchMedia('(max-width:760px)'),tabsHome=document.createComment('workspace-navigation');tabs.before(tabsHome);
  const syncMobileNavigation=()=>{const mobile=mobileLayout.matches;if(mobile)document.body.append(tabs);else tabsHome.after(tabs);const editing=document.querySelector('.qr-designer-panel').dataset.designView==='settings';head.querySelector('h2').textContent=mobile?'Ma capsule':'Personnaliser ma capsule';$('owner-tab-configuration').querySelector('span').textContent=mobile?'Capsule':'Personnalisation';edit.innerHTML=editing?'<i class="fa-solid fa-arrow-left" aria-hidden="true"></i> Aperçu':'<i class="fa-solid fa-sliders" aria-hidden="true"></i> Modifier';edit.setAttribute('aria-expanded',String(editing));};
  edit.onclick=()=>document.querySelector('[data-design-view="'+(document.querySelector('.qr-designer-panel').dataset.designView==='settings'?'preview':'settings')+'"]').click();
  window.addEventListener('suite-design-view',syncMobileNavigation);mobileLayout.addEventListener('change',syncMobileNavigation);syncMobileNavigation();
  // Reserve the measured heading height, including wrapped text and browser zoom.
  new ResizeObserver(()=>document.body.style.setProperty('--organizer-title-height',Math.ceil(head.getBoundingClientRect().height+12)+'px')).observe(head);
  document.querySelector('.qr-control-title').hidden=true;
  const design=document.querySelector('.qr-theme-gallery').closest('.customization-card');
  const designHeading=design.querySelector('h3,h4,strong');if(designHeading)designHeading.textContent='Style de la capsule';
  document.querySelectorAll('.qr-font-menu .qr-font-sample').forEach(e=>e.textContent='Votre événement');
  const colorGroup=document.querySelector('.qr-color-palette').closest('.customization-card');colorGroup.querySelector('h3,h4').textContent='Couleur du QR';
  const colorStatus=document.createElement('p');colorStatus.className='organizer-color-status';colorStatus.setAttribute('aria-live','polite');colorGroup.append(colorStatus);
  const syncColorChoice=()=>{const value=$('qr-color').value.toUpperCase();let name='Palette personnalisée';document.querySelectorAll('[data-qr-color]').forEach(b=>{const selected=b.dataset.qrColor.toUpperCase()===value;b.setAttribute('aria-pressed',String(selected));if(selected)name=b.getAttribute('aria-label');});const custom=document.querySelector('.qr-custom-color');custom.classList.toggle('is-selected',name==='Palette personnalisée');colorStatus.textContent=name+' · le contraste du QR est ajusté pour rester lisible.';};$('qr-color').addEventListener('input',syncColorChoice);$('qr-style').addEventListener('change',syncColorChoice);syncColorChoice();
  const personalization=document.querySelector('.qr-personalization-group');
  const compact=document.createElement('div');compact.className='organizer-compact-fields';
  const date=$('capsule-date').closest('.field'),dateHome=document.createComment('date');date.before(dateHome);
  const textGroup=$('print-title').closest('.qr-control-group'),title=$('print-title').closest('.field');title.querySelector('label').textContent='Titre de la fiche';compact.append(title,date);
  const settings=document.querySelector('[data-owner-panel=settings]');
  const relocateDate=()=>{if(!settings.hidden)dateHome.after(date);else title.after(date);};
  new MutationObserver(relocateDate).observe(settings,{attributes:true,attributeFilter:['hidden']});
  const nativeDate=date.querySelector('#capsule-date'),frenchDate=document.createElement('input');frenchDate.id='organizer-event-date';frenchDate.type='text';frenchDate.inputMode='numeric';frenchDate.maxLength=10;frenchDate.placeholder='JJ/MM/AAAA';frenchDate.autocomplete='off';frenchDate.setAttribute('aria-label','Date de l’événement, au format jour/mois/année');nativeDate.tabIndex=-1;nativeDate.after(frenchDate);date.querySelector('label').htmlFor=frenchDate.id;
  const calendar=document.createElement('button');calendar.type='button';calendar.className='organizer-date-picker';calendar.setAttribute('aria-label','Choisir la date dans le calendrier');calendar.innerHTML='<i class="fa-regular fa-calendar" aria-hidden="true"></i>';calendar.onclick=()=>{try{nativeDate.showPicker()}catch{nativeDate.focus()}};frenchDate.after(calendar);
  const dateError=document.createElement('small');dateError.id='organizer-event-date-error';dateError.className='organizer-date-error';dateError.hidden=true;dateError.setAttribute('role','status');date.append(dateError);frenchDate.setAttribute('aria-describedby',dateError.id);
  const dateFeedback=(valid,committed=false)=>{let message=valid?'':'Utilisez une date valide au format JJ/MM/AAAA.';const unchanged=c.status!=='draft'&&nativeDate.value===c.wedding_date;if(valid&&!nativeDate.disabled&&!unchanged){if(nativeDate.validity.rangeUnderflow)message='Choisissez une date à partir du '+nativeDate.min.split('-').reverse().join('/')+'.';else if(nativeDate.validity.rangeOverflow)message='Choisissez une date au plus tard le '+nativeDate.max.split('-').reverse().join('/')+'.';}frenchDate.setCustomValidity(message);const visible=Boolean(message)&&(committed||frenchDate.value.length===10);frenchDate.setAttribute('aria-invalid',String(visible));dateError.hidden=!visible;dateError.textContent=visible?message:'';return !message;};
  const syncDate=()=>{frenchDate.value=/^\d{4}-\d{2}-\d{2}$/.test(nativeDate.value)?nativeDate.value.split('-').reverse().join('/'):'';frenchDate.disabled=nativeDate.disabled;calendar.disabled=nativeDate.disabled;dateFeedback(Boolean(nativeDate.value));};
  const validateDate=(committed=false)=>{if(/^\d{3,8}$/.test(frenchDate.value)){const digits=frenchDate.value;frenchDate.value=digits.slice(0,2)+'/'+digits.slice(2,4)+(digits.length>4?'/'+digits.slice(4):'');}const match=frenchDate.value.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);const iso=match?match[3]+'-'+match[2]+'-'+match[1]:'';const parsed=new Date(iso+'T12:00:00Z');const valid=iso&&Number.isFinite(parsed.getTime())&&parsed.toISOString().slice(0,10)===iso;nativeDate.value=valid?iso:'';const accepted=dateFeedback(Boolean(valid),committed);nativeDate.dispatchEvent(new Event('input',{bubbles:true}));return accepted;};
  frenchDate.addEventListener('input',()=>validateDate());frenchDate.addEventListener('change',()=>{if(validateDate(true))nativeDate.dispatchEvent(new Event('change',{bubbles:true}));});nativeDate.addEventListener('input',event=>{if(event.isTrusted)syncDate()});nativeDate.addEventListener('change',syncDate);new MutationObserver(()=>{frenchDate.disabled=nativeDate.disabled;calendar.disabled=nativeDate.disabled;dateFeedback(Boolean(nativeDate.value));}).observe(nativeDate,{attributes:true,attributeFilter:['disabled','min','max']});syncDate();window.SuiteOrganizerLayout.syncDate=syncDate;window.addEventListener('studio-layout',syncDate);
  const note=$('print-note').closest('.field');note.querySelector('label[for=print-note]').textContent='Message sous le QR';compact.append(note);
  const welcome=document.createElement('div');welcome.className='field organizer-welcome-shortcut';welcome.innerHTML='<label>Accueil invités</label>';const welcomeButton=$('customize-welcome');welcomeButton.innerHTML='<i class="fa-regular fa-image" aria-hidden="true"></i><span>Personnaliser l’accueil</span><i class="fa-solid fa-pencil" aria-hidden="true"></i>';welcome.append(welcomeButton);personalization.after(compact);compact.after(welcome);
  let advanced=document.createElement('details');advanced.className='organizer-extra-options';advanced.open=true;advanced.innerHTML='<summary>Initiales et texte d’explication</summary>';advanced.append(textGroup,document.querySelector('.qr-initials-card'));compact.after(advanced);
  advanced.querySelector('label[for=qr-initials-input]').textContent='Initiales (4 caractères maximum)';
  const syncOptionalFields=()=>{if(mobileLayout.matches)$('qr-show-initials').checked=Boolean($('qr-initials-input').value.trim());for(const id of ['print-note','print-explanation']){const field=$(id),toggle=$(id+'-visible');if(mobileLayout.matches){toggle.checked=Boolean(field.value.trim());field.hidden=false;}else field.hidden=!toggle.checked;}};
  for(const id of ['print-note','print-explanation','qr-initials-input'])$(id).addEventListener('input',syncOptionalFields);mobileLayout.addEventListener('change',syncOptionalFields);syncOptionalFields();
  const syncOptionsContainer=()=>{const tag=mobileLayout.matches?'SECTION':'DETAILS';if(advanced.tagName===tag)return;const next=document.createElement(tag.toLowerCase());next.className='organizer-extra-options';const heading=document.createElement(mobileLayout.matches?'h3':'summary');heading.textContent='Initiales et texte d’explication';next.append(heading,...[...advanced.children].slice(1));if(!mobileLayout.matches)next.open=true;advanced.replaceWith(next);advanced=next;};mobileLayout.addEventListener('change',syncOptionsContainer);syncOptionsContainer();
  // Intro controls are edited in the existing welcome dialog, not duplicated on the page.
  $('organizer-welcome').classList.add('organizer-welcome-hidden');
  const preview=document.querySelector('.qr-designer-preview'),previewStage=document.querySelector('.qr-preview-stage');
  const stage=document.querySelector('.activation-panel');
  const placeActivation=()=>{if(!stage)return;if(document.body.classList.contains('visual-primary-ready')){const actions=document.querySelector('.visual-actions');if(actions)actions.append(stage);return;}if(!mobileLayout.matches)previewStage.after(stage);else if(document.querySelector('.qr-designer-panel').dataset.designView==='preview')preview.append(stage);else controls.append(stage);const availability=document.querySelector('.organizer-export-availability');if(availability){if(mobileLayout.matches){availability.textContent=c.usage?.state==='expired'?'Conservation terminée.':'Exports après activation · Fiche QR et accueil toujours modifiables.';stage.after(availability);}else{availability.textContent='Téléchargement, impression et partage disponibles après activation.';document.querySelector('.qr-preview-actions').after(availability);}}};
  window.SuiteOrganizerLayout.placeActivation=placeActivation;matchMedia('(max-width:760px)').addEventListener('change',placeActivation);placeActivation();
  const warning=document.createElement('p');warning.id='organizer-card-readability';warning.className='organizer-readability-warning';warning.hidden=true;warning.setAttribute('role','status');previewStage.after(warning);
  for(const id of ['print-title','print-note','print-explanation']){const field=$(id),hint=document.createElement('small');hint.id=id+'-fit';hint.className='organizer-text-fit';hint.hidden=true;hint.setAttribute('role','status');field.setAttribute('aria-describedby',hint.id);field.after(hint);}
  const full=document.createElement('dialog');full.id='organizer-card-preview-dialog';full.className='organizer-card-dialog';full.setAttribute('aria-labelledby','organizer-card-preview-title');full.innerHTML='<div class="organizer-card-dialog-head"><h2 id="organizer-card-preview-title">Votre fiche QR</h2><button type="button" aria-label="Fermer l’aperçu agrandi">×</button></div><img alt="Votre fiche QR en grand format"><p>Carte 10 × 15 cm · aperçu de l’impression</p>';$('dashboard-content').append(full);
  const artwork=$('qr-artwork-preview');const openFull=()=>{if(!$('design-welcome-preview').hidden){$('open-guest-link').click();return;}if(artwork.hidden||!artwork.src)return;full.querySelector('img').src=artwork.src;full.showModal();};artwork.tabIndex=0;artwork.setAttribute('role','button');artwork.setAttribute('aria-label','Agrandir l’aperçu de la fiche QR');artwork.onclick=openFull;artwork.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openFull();}});full.querySelector('button').onclick=()=>full.close();full.addEventListener('close',()=>artwork.focus());new MutationObserver(()=>{if(full.open)full.querySelector('img').src=artwork.src;}).observe(artwork,{attributes:true,attributeFilter:['src','hidden']});
  const actions=document.querySelector('.qr-preview-actions');actions.append($('download-print-card'),$('print-print-card'),$('share-link'));$('share-link').innerHTML='<i class="fa-solid fa-share-nodes" aria-hidden="true"></i>Partager le lien';
  $('print-print-card').classList.replace('primary','secondary');$('download-print-card').classList.replace('secondary','primary');
  const availability=document.createElement('p');availability.className='organizer-export-availability';availability.textContent=!$('download-print-card').disabled?'':c.usage?.state==='expired'?'La période de conservation est terminée.':'Téléchargement, impression et partage disponibles après activation.';availability.hidden=!$('download-print-card').disabled;actions.after(availability);const syncActions=()=>{const buttons=[...actions.querySelectorAll('button')];buttons.forEach(button=>button.hidden=button.disabled);actions.hidden=buttons.every(button=>button.disabled);availability.hidden=!actions.hidden;};const actionObserver=new MutationObserver(syncActions);actions.querySelectorAll('button').forEach(button=>actionObserver.observe(button,{attributes:true,attributeFilter:['disabled']}));syncActions();
  // Keep the full guest journey accessible without adding a fourth action to the row.
  const guide=document.querySelector('.qr-print-guide');guide.after($('open-guest-link'));$('open-guest-link').className='organizer-guest-preview-link';guide.innerHTML='<summary>Conseils d’impression</summary><p class="field-help">Imprimez sur A4 à 100 %, sans ajuster à la page. Découpez sur les repères pour obtenir une carte 10 × 15 cm.</p><p class="field-help">Placez-la dans un cadre ou sur un chevalet. Disposez plusieurs cartes sur les tables et partagez le lien aux absents.</p>';
  const guideHome=document.createComment('print-guide');guide.before(guideHome);
  const placePrintGuide=()=>{if(mobileLayout.matches){$('print-download-dialog').querySelector('.guest-dialog-body').append(guide);guide.open=false;}else guideHome.after(guide);placeActivation();};
  mobileLayout.addEventListener('change',placePrintGuide);placePrintGuide();
  if(c.print_title==='Notre capsule temporelle'&&c.couple_name){$('print-title').value=c.couple_name.slice(0,42);$('print-title').dispatchEvent(new Event('input',{bubbles:true}));}
  if(mobileLayout.matches)document.querySelector('[data-design-view=preview]').click();
  // Existing date locking, helper text and autosave continue to use the moved input.
 }};
})();

