/* One workspace: capsule selection, account settings and authorized service tools. */
(function(){
 'use strict';
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function sheet(id,title){
  const d=document.createElement('dialog');d.id=id;d.className='studio-sheet workspace-sheet';d.setAttribute('aria-labelledby',id+'-title');
  d.innerHTML='<div class="studio-sheet-head"><h2 id="'+id+'-title">'+title+'</h2><button type="button" class="studio-close" aria-label="Fermer">×</button></div><div class="studio-sheet-body"></div>';
  document.body.append(d);d.querySelector('.studio-close').onclick=()=>d.close();
  d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)if(!d.canClose||d.canClose())d.close()}});return d;
 }
 window.SuiteWorkspace={async setup({sb,user,caps,access,selected,canLeave,logout}){
  let ended=false,accountBusy=false,serviceBusy=false,member=false,adminLoaded=false,adminLoading=null,adminController=null;
  window.SuiteWorkspace.canExportCapsule=()=>member&&!ended;window.SuiteWorkspace.exportCapsule=async id=>{if(!member||ended)throw Error('Accès administrateur requis.');if(!canLeave())throw Error('Patientez jusqu’à la fin de la sauvegarde des modifications.');await loadAdmin();if(!adminController)throw Error('Le service est momentanément indisponible.');adminController.exportCapsule(id);};
  document.body.classList.add('workspace-ready');
  const header=document.querySelector('.suite-topbar');header.querySelector('[data-suite-burger]')?.remove();header.querySelector('[data-suite-nav]')?.remove();
  const accountButton=document.createElement('button');accountButton.id='workspace-account';accountButton.className='workspace-account-button';accountButton.type='button';accountButton.setAttribute('aria-label','Mon compte');accountButton.setAttribute('aria-haspopup','dialog');accountButton.innerHTML='<i class="fa-regular fa-user" aria-hidden="true"></i><span>Mon compte</span>';header.append(accountButton);
  const title=$('dashboard-title'),selector=document.createElement('button');selector.id='workspace-selector';selector.type='button';selector.className='workspace-selector';selector.setAttribute('aria-haspopup','dialog');selector.setAttribute('aria-label','Choisir une capsule');title.before(selector);selector.append(title);selector.insertAdjacentHTML('beforeend','<i class="fa-solid fa-chevron-down" aria-hidden="true"></i>');
  if(!selected)title.textContent='Mon espace';
  const choose=sheet('workspace-capsules','Mes capsules'),account=sheet('workspace-account-dialog','Mon compte'),service=sheet('workspace-administration','Administration');
  accountButton.setAttribute('aria-controls',account.id);selector.setAttribute('aria-controls',choose.id);
  const body=choose.querySelector('.studio-sheet-body');body.innerHTML='<div id="workspace-mine"><div id="workspace-capsule-list"></div><a id="workspace-create" class="btn primary" href="create.html"><i class="fa-solid fa-plus" aria-hidden="true"></i>Créer une capsule</a><p id="workspace-create-help" class="hint"></p></div><div id="workspace-service" hidden></div><p id="workspace-selection-status" class="status" role="status"></p>';
  $('workspace-create').hidden=!access.can_create;$('workspace-create-help').textContent=access.can_create?'':access.reason||'';
  function render(){$('workspace-capsule-list').innerHTML=caps.map(c=>'<a class="workspace-capsule-row" href="dashboard.html?slug='+encodeURIComponent(c.slug)+'" '+(c.slug===selected?.slug?'aria-current="true"':'')+'><img src="assets/themes/'+esc(c.qr_style||'minimal')+'.webp" alt=""><span><strong>'+esc(c.couple_name)+'</strong><small>'+esc(new Date(c.wedding_date+'T12:00:00').toLocaleDateString('fr-FR'))+'</small><small class="workspace-state">'+(c.status==='active'?'Active':'En préparation')+'</small></span><i class="fa-solid '+(c.slug===selected?.slug?'fa-check':'fa-chevron-right')+'" aria-hidden="true"></i></a>').join('')||'<p class="hint">'+(caps.length?'Aucune capsule ne correspond.':'Créez votre première capsule pour commencer.')+'</p>';}
  render();
  body.addEventListener('click',e=>{const link=e.target.closest('#workspace-mine a, #workspace-service a[href*="dashboard.html"], #workspace-service a[href="create.html"]');if(link&&!canLeave()){e.preventDefault();$('workspace-selection-status').textContent='Enregistrez les modifications avant de changer de capsule.'}});
  let scope='mine';async function switchScope(next){
   if(ended||serviceBusy||next==='all'&&!member)return;scope=next;$('workspace-capsules-title').textContent='Mes capsules';body.querySelectorAll('[data-workspace-scope]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.workspaceScope===next)));$('workspace-mine').hidden=next!=='mine';$('workspace-service').hidden=next!=='all';
   $('workspace-selection-status').textContent='';
   if(next==='all')try{await loadAdmin()}catch(e){$('workspace-selection-status').textContent='Gestion indisponible : '+e.message;}
  }
  body.querySelectorAll('[data-workspace-scope]').forEach(b=>b.onclick=()=>switchScope(b.dataset.workspaceScope));
  async function loadAdmin(){
   if(adminLoaded)return;if(adminLoading)return adminLoading;
   adminLoading=(async()=>{const r=await fetch('admin-panel.html?v=20261007-review8');if(!r.ok)throw Error('Rechargez la page pour réessayer.');const html=await r.text();if(ended||!member)return;$('workspace-service').innerHTML=html;if(access.can_create){const create=$('workspace-create').cloneNode(true);create.id='workspace-service-create';$('workspace-service').prepend(create);}
    const tools=document.querySelector('.workspace-service-tools');service.querySelector('.studio-sheet-body').append(tools);tools.open=true;document.querySelectorAll('#workspace-service .admin-dialog').forEach(d=>document.body.append(d));
    adminController=await window.initSuiteAdmin({client:sb,embedded:true,ownedCaps:caps,isActive:()=>choose.open&&scope==='all'||service.open||$('capsule-dialog')?.open,onBusy:value=>serviceBusy=value,onDenied:()=>{if(ended)return;member=false;window.dispatchEvent(new Event('suite-admin-status'));service.close();service.querySelector('.studio-sheet-body').replaceChildren();switchScope('mine');$('workspace-service').replaceChildren();}});if(ended)return;adminLoaded=true;
   })();try{await adminLoading}finally{adminLoading=null;}
  }
  service.canClose=()=>!serviceBusy;service.addEventListener('cancel',e=>{if(serviceBusy)e.preventDefault()});service.querySelector('.studio-close').onclick=()=>{if(!serviceBusy)service.close()};
  choose.canClose=()=>!serviceBusy;account.canClose=()=>!accountBusy;
  choose.addEventListener('cancel',e=>{if(serviceBusy)e.preventDefault()});choose.querySelector('.studio-close').onclick=()=>{if(!serviceBusy)choose.close()};
  selector.onclick=()=>{render();choose.showModal();if(member)switchScope('all')};choose.addEventListener('close',()=>{selector.focus()});
  account.querySelector('.studio-sheet-body').innerHTML='<section class="workspace-account-section"><h3>Adresse e-mail</h3><div class="workspace-email"><span id="workspace-email-current"></span><button id="workspace-edit-email" aria-expanded="false" aria-controls="workspace-email-form" class="btn secondary" type="button">Modifier</button></div><form id="workspace-email-form" hidden><label for="workspace-email-new">Nouvelle adresse e-mail</label><input id="workspace-email-new" type="email" autocomplete="email" required maxlength="254"><p class="hint">Confirmez le changement via les e-mails reçus. Votre adresse actuelle reste utilisée jusqu’à confirmation.</p><button class="btn primary" type="submit">Confirmer le changement</button></form></section><section class="workspace-account-section workspace-security" aria-label="Sécurité"><button id="workspace-edit-password" aria-expanded="false" aria-controls="workspace-password-form" class="workspace-account-row" type="button"><i class="fa-solid fa-lock" aria-hidden="true"></i>Modifier mon mot de passe<i class="fa-solid fa-chevron-down" aria-hidden="true"></i></button><form id="workspace-password-form" hidden><label for="workspace-password-current">Mot de passe actuel</label><input id="workspace-password-current" type="password" autocomplete="current-password" required><label for="workspace-password-new">Nouveau mot de passe</label><input id="workspace-password-new" type="password" autocomplete="new-password" minlength="10" required><label for="workspace-password-confirm">Confirmer le nouveau mot de passe</label><input id="workspace-password-confirm" type="password" autocomplete="new-password" minlength="10" required><small>Au moins 10 caractères.</small><button class="btn primary" type="submit">Modifier mon mot de passe</button><a href="auth.html?mode=reset">Mot de passe oublié ?</a></form></section><p id="workspace-account-status" class="status" role="status" aria-live="polite"></p><button id="logout" class="workspace-account-row workspace-logout" type="button"><i class="fa-solid fa-arrow-right-from-bracket" aria-hidden="true"></i>Déconnexion</button>';
  service.addEventListener('close',()=>accountButton.focus());
  let currentEmail=user.email||'';$('workspace-email-current').textContent=currentEmail;
  function report(text,error=false){const status=$('workspace-account-status');status.textContent=text;status.className='status show '+(error?'err':'ok');}
  function busy(value){accountBusy=value;account.querySelectorAll('button,input').forEach(b=>b.disabled=value);}
  accountButton.onclick=()=>{if(!ended){account.showModal()}};
  account.addEventListener('close',()=>{account.querySelectorAll('input[type=password]').forEach(i=>i.value='');['email','password'].forEach(kind=>{$('workspace-'+kind+'-form').hidden=true;$('workspace-edit-'+kind).setAttribute('aria-expanded','false')});$('workspace-account-status').textContent='';accountButton.focus()});
  account.addEventListener('cancel',e=>{if(accountBusy)e.preventDefault()});account.querySelector('.studio-close').onclick=()=>{if(!accountBusy)account.close()};
  $('workspace-edit-email').onclick=()=>{const f=$('workspace-email-form');f.hidden=!f.hidden;$('workspace-edit-email').setAttribute('aria-expanded',String(!f.hidden));if(!f.hidden){$('workspace-email-new').value=currentEmail;$('workspace-email-new').focus()}};
  $('workspace-edit-password').onclick=()=>{const f=$('workspace-password-form');f.hidden=!f.hidden;$('workspace-edit-password').setAttribute('aria-expanded',String(!f.hidden));if(!f.hidden)$('workspace-password-current').focus();else f.reset()};
  $('workspace-email-form').onsubmit=async e=>{e.preventDefault();if(ended||accountBusy)return;const email=$('workspace-email-new').value.trim();if(email.toLowerCase()===currentEmail.toLowerCase())return report('Cette adresse est déjà utilisée.');if(!e.target.reportValidity())return;busy(true);report('Envoi de la confirmation…');try{const {error}=await sb.auth.updateUser({email},{emailRedirectTo:new URL('dashboard.html',location.href).href});if(error)throw error;if(!ended)report('Demande envoyée. Consultez vos e-mails pour confirmer le changement.');}catch(e){if(!ended)report('Changement impossible : '+e.message,true)}finally{busy(false)}};
  $('workspace-password-form').onsubmit=async e=>{e.preventDefault();if(ended||accountBusy||!e.target.reportValidity())return;const old=$('workspace-password-current').value,password=$('workspace-password-new').value;if(password!==$('workspace-password-confirm').value)return report('Les nouveaux mots de passe ne correspondent pas.',true);if(password===old)return report('Choisissez un mot de passe différent de l’actuel.',true);busy(true);report('Modification en cours…');try{
   const checked=await sb.auth.signInWithPassword({email:currentEmail,password:old});if(checked.error)throw Error('Le mot de passe actuel est incorrect.');if(checked.data?.user&&checked.data.user.id!==user.id)throw Error('Le compte a changé. Reconnectez-vous.');if(ended)return;
   const {error}=await sb.auth.updateUser({password});if(error)throw error;if(!ended){e.target.reset();e.target.hidden=true;$('workspace-edit-password').setAttribute('aria-expanded','false');report('Votre mot de passe a été modifié.');}
  }catch(e){if(!ended)report('Modification impossible : '+e.message,true)}finally{busy(false)}};
  $('logout').onclick=async()=>{if(accountBusy||serviceBusy)return report('Patientez jusqu’à la fin de l’opération.',true);await logout();};
  sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||session?.user?.id&&session.user.id!==user.id){ended=true;member=false;choose.close();account.close();service.close();document.querySelectorAll('.admin-dialog[open]').forEach(d=>d.close());queueMicrotask(()=>{choose.replaceChildren();account.replaceChildren();service.replaceChildren()});document.querySelectorAll('.owner-tabs').forEach(n=>n.remove());}else if(event==='USER_UPDATED'&&session?.user?.email){currentEmail=session.user.email;$('workspace-email-current').textContent=currentEmail;}});
  // Server membership is authoritative; client profile metadata never grants access.
  (async()=>{try{let {data,error}=await sb.rpc('admin_status');if(error)throw error;let invite;try{invite=JSON.parse(localStorage.getItem('la_suite_admin_invite')||'null')}catch{}
   if(data!==true&&invite&&/^[a-f0-9]{64}$/.test(invite.token)&&Date.now()-invite.at<48*3600000){const claimed=await sb.rpc('admin_claim',{p_token:invite.token});if(claimed.error)throw claimed.error;({data,error}=await sb.rpc('admin_status'));if(error)throw error;}
   if(ended)return;member=data===true;window.dispatchEvent(new Event('suite-admin-status'));if(member){try{localStorage.removeItem('la_suite_admin_invite')}catch{}await switchScope('all');}
   if(new URLSearchParams(location.search).get('view')==='service'){choose.showModal();if(member)await switchScope('all');else $('workspace-selection-status').textContent='Ce compte ne dispose pas d’un accès administrateur.';}
  }catch(e){if(!ended&&new URLSearchParams(location.search).get('view')==='service'){choose.showModal();$('workspace-selection-status').textContent='Vérification de l’accès impossible. Rechargez la page.';}}})();
  // Follow the visual viewport while Android browser bars expand/collapse.
  const viewport=window.visualViewport;let frame;
  function align(){cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(ended)return;const visible=window.visualViewport,zoomed=visible&&Math.abs(visible.scale-1)>.05;const gap=visible&&!zoomed?Math.max(0,innerHeight-visible.height-visible.offsetTop):0;document.documentElement.style.setProperty('--workspace-bottom',gap+'px');document.documentElement.style.setProperty('--workspace-viewport-height',(visible&&!zoomed?visible.height:innerHeight)+'px');document.body.classList.toggle('workspace-keyboard',!!visible&&!zoomed&&innerHeight-visible.height>150);if(account.open&&account.contains(document.activeElement)&&document.activeElement.matches('input'))document.activeElement.scrollIntoView({block:'nearest'});});}
  viewport?.addEventListener('resize',align);viewport?.addEventListener('scroll',align);window.addEventListener('resize',align);window.addEventListener('scroll',align,{passive:true});align();
 }};
})();
