const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),assert=require('assert');
const path=require('path');
const root=path.resolve(__dirname,'..');
const modules=process.env.QA_NODE_MODULES||path.join(__dirname,'node_modules');
const screenshots=process.env.QA_SCREENSHOTS||require('os').tmpdir();
const eventYear=new Date().getFullYear()+1;
const baseCaps={id:'11111111-1111-4111-8111-111111111111',owner_id:'owner',slug:'julie-thomas',guest_token:'abc'.repeat(12),couple_name:'Julie & Thomas',wedding_date:eventYear+'-06-12',plan:'premium',status:'draft',created_at:new Date().toISOString()};
(async()=>{
 const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://local').pathname;if(p==='/')p='/index.html';try{const data=fs.readFileSync(root+p);res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'text/html');res.end(data)}catch(e){res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');
 await new Promise(resolve=>server.once('listening',resolve));
 const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-gpu','--no-zygote']});
 const context=await browser.newContext({viewport:{width:390,height:844}});
 await context.route('**/*',async route=>{const u=route.request().url();if(u.startsWith(base))return route.continue();if(u.includes('font-awesome')&&u.endsWith('.css'))return route.fulfill({contentType:'text/css',body:fs.readFileSync(modules+'/@fortawesome/fontawesome-free/css/all.min.css','utf8')});
 if(u.includes('/webfonts/'))return route.fulfill({contentType:'font/woff2',body:fs.readFileSync(modules+'/@fortawesome/fontawesome-free/webfonts/'+u.split('/').pop())});
 if(u.includes('fonts.googleapis.com')){let css='';for(const [name,pkg] of [['Inter','inter'],['Cormorant Garamond','cormorant-garamond']])for(const weight of [400,600,700]){const data=fs.readFileSync(modules+'/@fontsource/'+pkg+'/files/'+pkg+'-latin-'+weight+'-normal.woff2').toString('base64');css+=`@font-face{font-family:'${name}';font-weight:${weight};src:url(data:font/woff2;base64,${data})}`;}return route.fulfill({contentType:'text/css',body:css})}
 if(u.includes('qrcodejs'))return route.fulfill({contentType:'application/javascript',body:fs.readFileSync(modules+'/qrcodejs/qrcode.min.js','utf8')});return route.fulfill({body:'',contentType:'application/javascript'})});
 await context.addInitScript(({cap})=>{
  window._calls=[];let caps=JSON.parse(localStorage.getItem('testCaps')||JSON.stringify([cap]));
  const call=(type,data)=>window._calls.push({type,data});
  const getUser=()=>localStorage.getItem('logged')?{id:'owner',email:'test@example.com'}:null;
  const auth={getUser:async()=>({data:{user:getUser()}}),onAuthStateChange:fn=>{window._authEvent=fn},signOut:async()=>{localStorage.removeItem('logged')},resend:async data=>{call('resend',data);return{}},signUp:async data=>{call('signup',data);return{data:{session:null}}},signInWithPassword:async data=>{call('login',data);if(data.password==='correctpassword'){localStorage.setItem('logged','yes');return{data:{session:{}}}}return{error:{message:'Invalid login credentials'}}},resetPasswordForEmail:async(...data)=>{call('reset',data);return{}},updateUser:async data=>{call('password',data);return{error:{message:'Test update stopped'}}}};
  window.supabase={createClient:()=>({auth,from:table=>{
   let op='select',payload,filter;
   const run=()=>{if(op==='insert'){call('insert',payload);caps.push({...cap,...payload});localStorage.setItem('testCaps',JSON.stringify(caps));return{data:{...cap,...payload}}}if(op==='update'){call('update',payload);if(window._failUpdate)return{error:{message:'Échec simulé'}};caps=caps.map(c=>!filter||c[filter[0]]===filter[1]?{...c,...payload}:c);localStorage.setItem('testCaps',JSON.stringify(caps));return{data:null}}return{data:filter?caps.find(c=>c[filter[0]]===filter[1])||null:caps}};
   const chain={select:()=>chain,insert:p=>{op='insert';payload=p;return chain},update:p=>{op='update';payload=p;return chain},eq:(k,v)=>{filter=[k,v];return chain},order:async()=>run(),single:async()=>run(),maybeSingle:async()=>run(),then:(resolve,reject)=>Promise.resolve(run()).then(resolve,reject)};return chain;
  },rpc:async(name,args)=>{call(name,args);if(name==='activate_capsule'){caps=caps.map(c=>c.id===args.p_capsule_id?{...c,status:'active'}:c);localStorage.setItem('testCaps',JSON.stringify(caps));return{}}if(name==='get_capsule_public')return{data:caps.filter(c=>c.status==='active').map(c=>({...c,has_intro:!!c.intro_path}))};return{data:[]}},functions:{invoke:async()=>({data:{signed_url:'/assets/la-suite-logo.webp',media_type:'image'}})},storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:'/assets/la-suite-logo.webp'}}),upload:async(path,file)=>{call('upload',{path,type:file.type});return{data:{path}}}})}})};
 },{cap:baseCaps});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/auth.html');await page.locator('#email').fill('test@example.com');await page.locator('#password').fill('wrong');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('incorrect'));assert.equal(await page.locator('button[type=submit]').isDisabled(),false);
 await page.locator('[data-auth-mode=signup]').click();await page.locator('#password').fill('longpassword123');await page.locator('#password-confirm').fill('differentpass');await page.locator('button[type=submit]').click();assert.match(await page.locator('#status').innerText(),/correspondent/);
 await page.locator('#password-confirm').fill('longpassword123');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('confirmer'));assert(await page.evaluate(()=>_calls.some(c=>c.type==='signup')));await page.locator('#resend-confirmation').click();assert(await page.evaluate(()=>_calls.some(c=>c.type==='resend')));
 await page.locator('[data-auth-mode=reset]').click();await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('associée'));assert(await page.evaluate(()=>_calls.some(c=>c.type==='reset')));
 await page.goto(base+'/auth.html?mode=recovery');assert(await page.locator('#email').isHidden());await page.locator('#password').fill('newpassword123');await page.locator('#password-confirm').fill('newpassword123');await page.locator('button[type=submit]').click();assert(await page.evaluate(()=>_calls.some(c=>c.type==='password')));
 await page.goto(base+'/auth.html');await page.locator('#email').fill('test@example.com');await page.locator('#password').fill('correctpassword');await page.locator('button[type=submit]').click();await page.waitForURL('**/dashboard.html');await page.waitForSelector('.capsule-card');await page.evaluate(()=>localStorage.removeItem('logged'));
 await page.goto(base+'/create.html?plan=audio');assert.equal(await page.locator('#plan').inputValue(),'audio');await page.locator('#couple').fill('Anne & Paul');await page.locator('#wedding_date_display').fill('12/06/'+eventYear);await page.locator('#email').fill('test@example.com');await page.locator('button[type=submit]').click();await page.waitForURL('**/auth.html?mode=signup&next=create');assert.equal(await page.locator('#email').inputValue(),'test@example.com');
 await page.evaluate(()=>localStorage.setItem('logged','yes'));await page.goto(base+'/create.html?resume=1');await page.waitForURL('**/dashboard.html?slug=*');await page.waitForSelector('#review-activation');assert(await page.locator('#share-link').isDisabled());assert(await page.locator('#open-guest-link').isHidden());
 await page.locator('#review-activation').click();await page.locator('#activation-dialog').waitFor({state:'visible'});assert.match(await page.locator('#activation-dialog').innerText(),/Écho/);await page.locator('#activate-capsule').click();await page.waitForFunction(()=>document.querySelector('.activation-panel')?.textContent.includes('Capsule active'));assert.equal(await page.locator('#share-link').isDisabled(),false);

 assert.equal(await page.locator('#print-title').inputValue(),'Notre capsule temporelle');
 assert.match(await page.locator('#print-explanation').inputValue(),/une photo, un audio ou un texte/);
 assert.equal(await page.locator('#print-note').getAttribute('maxlength'),'120');
 assert.equal(await page.locator('#intro-kind').inputValue(),'none');
 await page.locator('#intro-kind').selectOption('text');await page.locator('#intro-text').fill('Bienvenue dans notre capsule !');await page.locator('#upload-intro').click();await page.waitForFunction(()=>document.querySelector('#intro-status').textContent.includes('est enregistré'));assert.match(await page.locator('#intro-preview-wrap').innerText(),/Bienvenue/);
 await page.evaluate(()=>window._failUpdate=true);await page.locator('#intro-text').fill('Ne doit pas être enregistré');await page.locator('#upload-intro').click();assert.match(await page.locator('#intro-status').innerText(),/Échec/);assert.match(await page.locator('#intro-preview-wrap').innerText(),/Bienvenue/);await page.evaluate(()=>window._failUpdate=false);
 await page.locator('#intro-kind').selectOption('image');await page.locator('#intro-file').setInputFiles({name:'greeting.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRhcAAAAASUVORK5CYII=','base64')});await page.locator('#upload-intro').click();await page.waitForSelector('#intro-preview-wrap img');assert(await page.evaluate(()=>_calls.some(c=>c.type==='upload'&&c.data.type==='image/png')));
 const ownerUrl=page.url();await page.goto(base+'/capsule.html?t='+baseCaps.guest_token);await page.waitForSelector('#organizer-intro-image');assert(await page.locator('#organizer-intro').isHidden());await page.goto(ownerUrl);await page.waitForSelector('#intro-kind');assert.equal(await page.locator('#intro-kind').inputValue(),'image');
 await page.locator('#intro-kind').selectOption('video');await page.locator('#intro-file').setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});await page.locator('#upload-intro').click();assert.match(await page.locator('#intro-status').innerText(),/MP4/);
 await page.locator('#intro-file').setInputFiles({name:'greeting.webm',mimeType:'video/webm',buffer:Buffer.from('GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAASOEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZUrmtTrIHYTbuMU6uEElTDZ1OsggEeTbuMU6uEHFO7a1OsggR47AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsirXsYMPQkBNgI1MYXZmNjAuMTYuMTAwV0GNTGF2ZjYwLjE2LjEwMESJiECPQAAAAAAAFlSua8GuAQAAAAAAADjXgQFzxYj4aeWw3TPuLJyBACK1nIN1bmSIgQCGhVZfVlA4g4EBI+ODhAJiWgDgibCBoLqBeJqBAhJUw2f8c3OgY8CAZ8iaRaOHRU5DT0RFUkSHjUxhdmY2MC4xNi4xMDBzc9ZjwItjxYj4aeWw3TPuLGfIoUWjh0VOQ09ERVJEh5RMYXZjNjAuMzEuMTAyIGxpYnZweGfIoUWjiERVUkFUSU9ORIeTMDA6MDA6MDEuMDAwMDAwMDAwAB9DtnVC0+eBAKPegQAAgPAGAJ0BKqAAeAAARwiFhYiFhIgCAgJ1qgP4AgaTjwUQnFLSoTilpUJxS0qE4paVCcUtKhOKWlQnFLSoTilpUJsA/v9NEv/8WFfxYV/FhX/xYV/8/M7txfzmAKOYgQAoABECAAUQrAAYABhYL/QACICBDLAAo5iBAFAAEQIABRCsABgAGFgv9AAIgIEMsACjmIEAeAARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQCgABECAAUQrAAYABhYL/QACICBDLAAo5iBAMgAEQIABRCsABgAGFgv9AAIgIEMsACjmIEA8AARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQEYABECAAUQEBRgAGFgv9AAIgIEMsAAo5iBAUAAEQIABRCsABgAGFgv9AAIgIEMsACjmIEBaAARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQGQABECAAUQrAAYABhYL/QACICBDLAAo5iBAbgAEQIABRCsABgAGFgv9AAIgIEMsACjmIEB4AARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQIIABECAAUQrAAYABhYL/QACICBDLAAo5iBAjAAEQIABRCsABgAGFgv9AAIgIEMsACjmIECWAARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQKAABECAAUQrAAYABhYL/QACICBDLAAo5iBAqgAEQIABRCsABgAGFgv9AAIgIEMsACjmIEC0AARAgAFEBAUYABhYL/QACICBDLAAKOYgQL4ABECAAUQrAAYABhYL/QACICBDLAAo5iBAyAAEQIABRCsABgAGFgv9AAIgIEMsACjmIEDSAARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQNwABECAAUQrAAYABhYL/QACICBDLAAo5iBA5gAEQIABRCsABgAGFgv9AAIgIEMsACjmIEDwAARAgAFEKwAGAAYWC/0AAiAgQywABxTu2uRu4+zgQC3iveBAfGCAZ/wgQM=','base64')});await page.locator('#upload-intro').click();await page.waitForSelector('#intro-preview-wrap video');assert(await page.evaluate(()=>_calls.some(c=>c.type==='upload'&&c.data.type==='video/webm')));
 await page.locator('#intro-kind').selectOption('none');await page.locator('#upload-intro').click();await page.waitForFunction(()=>document.querySelector('#intro-status').textContent.includes('désactivé'));assert.equal(await page.locator('#intro-preview-wrap img').count(),0);
 await page.screenshot({path:path.join(screenshots,'configuration-mobile.png'),fullPage:true});
 await page.locator('#qr-artwork-preview').screenshot({path:path.join(screenshots,'configuration-card.png')});
 await page.goto(base+'/dashboard.html');await page.waitForSelector('.capsule-card');assert.equal(await page.locator('.capsule-card').count(),3);await page.screenshot({path:path.join(screenshots,'account-mobile.png'),fullPage:true});
 for(const width of [390,1280]){await page.setViewportSize({width,height:900});await page.goto(base+'/index.html');assert.match(await page.locator('h1').innerText(),/découvrir/);assert.equal(await page.locator('.pricing-card').nth(1).locator('.pricing-icon i').count(),2);assert.equal(await page.locator('.pricing-card').nth(2).locator('.pricing-icon i').count(),3);assert.equal(await page.locator('.formats-block').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(screenshots,'home-'+width+'.png'),fullPage:true})}
 assert.deepEqual(errors,[]);console.log('PASS: login, signup confirmation, password mismatch/reset/recovery, preserved creation, plan, private draft controls, activation, capsule list, cumulative icons, responsive layout, optional text/image/video greeting, guest image display and save errors');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
