const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),assert=require('assert');
const path=require('path');
const root=path.resolve(__dirname,'..');
const modules=process.env.QA_NODE_MODULES||path.join(__dirname,'node_modules');
const screenshots=process.env.QA_SCREENSHOTS||require('os').tmpdir();
const eventYear=new Date().getFullYear()+1;
const baseCaps={id:'11111111-1111-4111-8111-111111111111',owner_id:'owner',slug:'julie-thomas',guest_token:'abc'.repeat(12),couple_name:'Julie & Thomas',wedding_date:eventYear+'-06-12',plan:'premium',status:'draft',created_at:new Date().toISOString()};
(async()=>{
 const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://local').pathname;if(p==='/')p='/index.html';try{const data=fs.readFileSync(root+p);res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.webp')?'image/webp':'text/html');res.end(data)}catch(e){res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');
 await new Promise(resolve=>server.once('listening',resolve));
 const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-gpu','--no-zygote']});
 const context=await browser.newContext({viewport:{width:390,height:844}});
 await context.route('**/*',async route=>{const u=route.request().url();if(u.startsWith(base)&&new URL(u).pathname==='/app.js')return route.fulfill({contentType:'application/javascript',body:fs.readFileSync(root+'/app.js','utf8').replace('initAuth();initCreate();initCapsule();initDashboard();','window.__card={buildPrintCardCanvas,qrOptions};initAuth();initCreate();initCapsule();initDashboard();')});if(u.startsWith(base))return route.continue();if(u.includes('font-awesome')&&u.endsWith('.css'))return route.fulfill({contentType:'text/css',body:fs.readFileSync(modules+'/@fortawesome/fontawesome-free/css/all.min.css','utf8')});
 if(u.includes('/webfonts/'))return route.fulfill({contentType:'font/woff2',body:fs.readFileSync(modules+'/@fortawesome/fontawesome-free/webfonts/'+u.split('/').pop())});
 if(u.includes('fonts.googleapis.com')){let css='';for(const [name,pkg] of [['Inter','inter'],['Cormorant Garamond','cormorant-garamond']])for(const weight of [400,600,700]){const data=fs.readFileSync(modules+'/@fontsource/'+pkg+'/files/'+pkg+'-latin-'+weight+'-normal.woff2').toString('base64');css+=`@font-face{font-family:'${name}';font-weight:${weight};src:url(data:font/woff2;base64,${data})}`;}return route.fulfill({contentType:'text/css',body:css})}
 if(u.includes('qrcodejs'))return route.fulfill({contentType:'application/javascript',body:fs.readFileSync(modules+'/qrcodejs/qrcode.min.js','utf8')});return route.fulfill({body:'',contentType:'application/javascript'})});
 await context.addInitScript(({cap})=>{
  window.showSaveFilePicker=undefined;window._calls=[];let caps=JSON.parse(localStorage.getItem('testCaps')||JSON.stringify([cap]));
  const call=(type,data)=>window._calls.push({type,data});
  const getUser=()=>localStorage.getItem('logged')?{id:'owner',email:'test@example.com'}:null;
  const auth={getUser:async()=>({data:{user:getUser()}}),onAuthStateChange:fn=>{window._authEvent=fn},signOut:async()=>{localStorage.removeItem('logged')},resend:async data=>{call('resend',data);return{}},signUp:async data=>{call('signup',data);return{data:{session:null}}},signInWithPassword:async data=>{call('login',data);if(data.password==='correctpassword'){localStorage.setItem('logged','yes');return{data:{session:{}}}}return{error:{message:'Invalid login credentials'}}},resetPasswordForEmail:async(...data)=>{call('reset',data);return{}},updateUser:async data=>{call('password',data);return{error:{message:'Test update stopped'}}}};
  window.supabase={createClient:()=>({auth,from:table=>{
   let op='select',payload,filters=[];
   const matches=c=>filters.every(([key,value])=>c[key]===value);
   const run=()=>{
    if(table==='messages')return window._failMessages?{error:{message:'Messages indisponibles'}}:{data:window._messageRows||[]};
    if(op==='insert'){call('insert',payload);caps.push({...cap,...payload});localStorage.setItem('testCaps',JSON.stringify(caps));return{data:{...cap,...payload}}}
    if(op==='update'){call('update',payload);if(window._failUpdate)return{error:{message:'Échec simulé'}};if(window._emptyUpdate)return{data:null};const selected=caps.find(matches);caps=caps.map(c=>matches(c)?{...c,...payload}:c);localStorage.setItem('testCaps',JSON.stringify(caps));return{data:selected?{id:selected.id}:null}}
    if(op==='delete'){call('delete',filters);if(window._failDelete)return{error:{message:'Suppression indisponible'}};const removed=caps.filter(matches);caps=caps.filter(c=>!matches(c));localStorage.setItem('testCaps',JSON.stringify(caps));return{data:removed.map(c=>({id:c.id}))}}
    return{data:filters.length?caps.find(matches)||null:caps};
   };
   const chain={select:()=>chain,insert:p=>{op='insert';payload=p;return chain},update:p=>{op='update';payload=p;return chain},delete:()=>{op='delete';return chain},eq:(k,v)=>{filters.push([k,v]);return chain},order:async()=>run(),single:async()=>window._writeDelay&&op==='update'?await new Promise(r=>setTimeout(()=>r(run()),window._writeDelay)):run(),maybeSingle:async()=>run(),then:(resolve,reject)=>Promise.resolve(window._writeDelay&&op==='update'?new Promise(r=>setTimeout(()=>r(run()),window._writeDelay)):run()).then(resolve,reject)};return chain;
  },rpc:async(name,args)=>{call(name,args);if(name==='owner_capsule_access')return{data:{free_launch:true,can_create:caps.length===0,existing_slug:caps[0]?.slug,reason:'Le lancement gratuit comprend une seule capsule par compte.'}};if(name==='owner_capsule_usage')return{data:window._usage||{state:'scheduled',quota_bytes:5000000000,used_bytes:0,opens_at:cap.wedding_date+'T00:00:00Z',closes_at:cap.wedding_date+'T23:59:59Z',expires_at:(Number(cap.wedding_date.slice(0,4))+3)+'-06-12T00:00:00Z',delivery_before:(Number(cap.wedding_date.slice(0,4))+2)+'-12-12T00:00:00Z'}};if(name==='owner_export_bundle')return{data:window._exportBundle||{name:'Julie & Thomas',date:cap.wedding_date,messages:[{guest_name:'Alice',message_text:'Un beau souvenir',media_type:'text',delivery_at:new Date().toISOString(),path:null}]}};if(name==='owner_message_manifest'&&window._revealAt&&Date.now()>=window._revealAt)window._manifest[0].is_available=true;if(name==='owner_message_manifest')return window._failManifest?{error:{message:'Indisponible'}}:{data:window._manifest||[]};if(name==='owner_capsule_stats')return{data:[{message_count:2}]};if(name==='activate_capsule'){caps=caps.map(c=>c.id===args.p_capsule_id?{...c,status:'active'}:c);localStorage.setItem('testCaps',JSON.stringify(caps));return{}}if(name==='get_capsule_public')return{data:caps.filter(c=>c.status==='active').map(c=>({...c,has_intro:!!c.intro_path}))};return{data:[]}},functions:{invoke:async(_,{body})=>body.action==='init_intro'?{data:{path:cap.id+'/organizer/intro-test.'+(body.file_type.startsWith('video/')?'webm':'png'),token:'signed-token'}}:body.action==='finalize_intro'?(caps=caps.map(c=>c.id===body.capsule_id?{...c,intro_path:body.path,welcome_message:null}:c),localStorage.setItem('testCaps',JSON.stringify(caps)),{data:{ok:true}}):body.action==='get_status'?{data:{...caps.find(c=>c.status==='active'),state:'open',effective_plan:'premium',has_intro:!!caps.find(c=>c.status==='active')?.intro_path,delivery_before:'2029-12-12T00:00:00Z',closes_at:'2027-06-14T00:00:00Z'}}:{data:{signed_url:'/assets/la-suite-logo.webp',media_type:'image'}}},storage:{from:()=>({createSignedUrl:async(...args)=>{call('signed',args);return window._failSigned?{error:{message:'Indisponible'}}:{data:{signedUrl:'/assets/la-suite-logo.webp'}}},uploadToSignedUrl:async(path,token,file)=>{call('upload',{path,type:file.type});return{data:{path}}}})}})};
 },{cap:baseCaps});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/auth.html');await page.locator('#email').fill('test@example.com');await page.locator('#password').fill('wrong');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('incorrect'));assert.equal(await page.locator('button[type=submit]').isDisabled(),false);
 await page.locator('[data-auth-mode=signup]').click();await page.locator('#password').fill('longpassword123');await page.locator('#password-confirm').fill('differentpass');await page.locator('button[type=submit]').click();assert.match(await page.locator('#status').innerText(),/correspondent/);
 await page.locator('#password-confirm').fill('longpassword123');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('confirmer'));assert(await page.evaluate(()=>_calls.some(c=>c.type==='signup')));await page.locator('#resend-confirmation').click();assert(await page.evaluate(()=>_calls.some(c=>c.type==='resend')));
 await page.locator('[data-auth-mode=reset]').click();await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('associée'));assert(await page.evaluate(()=>_calls.some(c=>c.type==='reset')));
 await page.goto(base+'/auth.html?mode=recovery');assert(await page.locator('#email').isHidden());await page.locator('#password').fill('newpassword123');await page.locator('#password-confirm').fill('newpassword123');await page.locator('button[type=submit]').click();assert(await page.evaluate(()=>_calls.some(c=>c.type==='password')));
 await page.goto(base+'/auth.html');await page.locator('#email').fill('test@example.com');await page.locator('#password').fill('correctpassword');await page.locator('button[type=submit]').click();await page.waitForURL('**/dashboard.html?slug=*');await page.waitForSelector('#review-activation');await page.evaluate(()=>{localStorage.removeItem('logged');localStorage.setItem('testCaps','[]')});
 await page.goto(base+'/create.html?plan=audio');
 for(const width of [390,1280]){await page.setViewportSize({width,height:900});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(screenshots,'create-'+width+'.png'),fullPage:true})}
 await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('#plan').inputValue(),'audio');await page.locator('#couple').fill('Anne & Paul');await page.locator('#wedding_date_display').fill('12/06/'+eventYear);await page.locator('#email').fill('test@example.com');await page.locator('button[type=submit]').click();await page.waitForURL('**/auth.html?mode=signup&next=create');assert.equal(await page.locator('#email').inputValue(),'test@example.com');
 await page.evaluate(()=>localStorage.setItem('logged','yes'));await page.goto(base+'/create.html?resume=1');await page.waitForURL('**/dashboard.html?slug=*');await page.waitForSelector('#review-activation');assert(await page.locator('#share-link').isDisabled());assert(await page.locator('#open-guest-link').isHidden());
 // Pending changes must survive activation, and failed writes must block it.
 const originalNote=await page.locator('#print-note').inputValue();
 await page.evaluate(()=>window._failUpdate=true);await page.locator('#print-note').fill('Un souvenir à garder');
 assert(await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});dispatchEvent(e);return e.defaultPrevented}));
 await page.waitForFunction(()=>document.querySelector('#organizer-save-state').dataset.state==='error');
 await page.locator('#review-activation').click();assert(await page.locator('#activation-dialog').isHidden());assert(!await page.evaluate(()=>_calls.some(c=>c.type==='activate_capsule')));
 await page.evaluate(()=>{window._failUpdate=false;window._emptyUpdate=true});await page.locator('#print-note').fill('Ne pas afficher un faux succès');await page.waitForFunction(()=>document.querySelector('#organizer-save-state').dataset.state==='error');await page.locator('#review-activation').click();assert(await page.locator('#activation-dialog').isHidden());assert(!await page.evaluate(()=>_calls.some(c=>c.type==='activate_capsule')));await page.evaluate(()=>window._emptyUpdate=false);await page.locator('#print-note').fill(originalNote);
 await page.locator('#intro-kind').selectOption('text');await page.locator('#intro-text').fill('Accueil sauvegardé avant activation');assert.match(await page.locator('#intro-live-preview').innerText(),/Accueil sauvegardé/);
 await page.locator('.capsule-settings summary').click();await page.locator('#capsule-name').fill('Anne & Paul — notre capsule');await page.locator('#capsule-plan').selectOption('photo');
 await page.waitForFunction(()=>document.querySelector('#organizer-save-state').textContent==='Tout est enregistré'&&document.querySelector('#dashboard-title').textContent==='Anne & Paul — notre capsule');assert.equal(await page.locator('#dashboard-title').innerText(),'Anne & Paul — notre capsule');assert.match(await page.locator('#print-explanation').inputValue(),/une photo ou un texte/);

 await page.evaluate(()=>window._writeDelay=350);await page.locator('#print-title').fill('Premier titre');await page.waitForFunction(()=>document.querySelector('#organizer-save-state').textContent==='Enregistrement…');await page.locator('#print-title').fill('Dernier titre');await page.waitForFunction(()=>document.querySelector('#organizer-save-state').textContent==='Tout est enregistré');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('testCaps')).find(c=>c.couple_name.includes('Anne')).print_title),'Dernier titre');
 await page.evaluate(()=>window._writeDelay=0);await page.locator('#print-title').fill('Notre capsule temporelle');
 await page.locator('#capsule-plan').selectOption('audio');await page.locator('#intro-text').fill('Dernier accueil à conserver');
 assert(await page.evaluate(()=>document.querySelector('.intro-video-panel').compareDocumentPosition(document.querySelector('.activation-panel'))&Node.DOCUMENT_POSITION_FOLLOWING));await page.locator('#review-activation').click();await page.locator('#activation-dialog').waitFor({state:'visible'});assert.match(await page.locator('#activation-dialog').innerText(),/Plus/);await page.locator('#activate-capsule').click();await page.waitForFunction(()=>document.querySelector('.activation-panel')?.textContent.includes('Capsule active'));assert.equal(await page.locator('#share-link').isDisabled(),false);

 await page.locator('.capsule-settings summary').click();await page.locator('#capsule-suggestion').selectOption('12');await page.waitForFunction(()=>_calls.some(c=>c.type==='update'&&c.data.suggested_delivery_months===12));await page.locator('.capsule-settings summary').click();
 assert.equal(await page.locator('#print-title').inputValue(),'Notre capsule temporelle');
 assert.match(await page.locator('#print-explanation').inputValue(),/une photo, un audio ou un texte/);
 assert.equal(await page.locator('#print-note').getAttribute('maxlength'),'120');
 assert.equal(await page.locator('#intro-kind').inputValue(),'text');assert.equal(await page.locator('#intro-text').inputValue(),'Dernier accueil à conserver');assert.equal(await page.locator('.activation-success .btn').count(),3);
 await page.locator('#intro-kind').selectOption('text');await page.locator('#intro-text').fill('Bienvenue dans notre capsule !');await page.evaluate(()=>window._writeDelay=300);await page.locator('#upload-intro').click();await page.locator('#save-organizer').click();await page.waitForFunction(()=>document.querySelector('#organizer-save-state').textContent==='Tout est enregistré');assert.equal(await page.evaluate(()=>_calls.filter(c=>c.type==='update'&&c.data.welcome_message==='Bienvenue dans notre capsule !').length),1);await page.evaluate(()=>window._writeDelay=0);await page.waitForFunction(()=>document.querySelector('#intro-status').textContent.includes('est enregistré'));assert.match(await page.locator('#intro-preview-wrap').innerText(),/Bienvenue/);
 await page.evaluate(()=>window._failUpdate=true);await page.locator('#intro-text').fill('Ne doit pas être enregistré');await page.locator('#upload-intro').click();assert.match(await page.locator('#intro-status').innerText(),/Échec/);assert.match(await page.locator('#intro-preview-wrap').innerText(),/Bienvenue/);assert.match(await page.locator('#intro-live-preview').innerText(),/Ne doit pas/);await page.evaluate(()=>window._failUpdate=false);
 await page.locator('#intro-kind').selectOption('image');await page.locator('#intro-file').setInputFiles({name:'greeting.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRhcAAAAASUVORK5CYII=','base64')});await page.locator('#upload-intro').click();await page.waitForSelector('#intro-preview-wrap img');assert(await page.evaluate(()=>_calls.some(c=>c.type==='upload'&&c.data.type==='image/png')));
 const ownerUrl=page.url();await page.goto(base+'/capsule.html?t='+baseCaps.guest_token);await page.waitForSelector('#organizer-intro-image');assert(await page.locator('#organizer-intro').isHidden());await page.goto(ownerUrl);await page.waitForSelector('#intro-kind');assert.equal(await page.locator('#intro-kind').inputValue(),'image');
 await page.locator('#intro-kind').selectOption('video');await page.locator('#intro-file').setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});await page.locator('#upload-intro').click();assert.match(await page.locator('#intro-status').innerText(),/MP4/);
 await page.locator('#intro-file').setInputFiles({name:'greeting.webm',mimeType:'video/webm',buffer:Buffer.from('GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAASOEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZUrmtTrIHYTbuMU6uEElTDZ1OsggEeTbuMU6uEHFO7a1OsggR47AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsirXsYMPQkBNgI1MYXZmNjAuMTYuMTAwV0GNTGF2ZjYwLjE2LjEwMESJiECPQAAAAAAAFlSua8GuAQAAAAAAADjXgQFzxYj4aeWw3TPuLJyBACK1nIN1bmSIgQCGhVZfVlA4g4EBI+ODhAJiWgDgibCBoLqBeJqBAhJUw2f8c3OgY8CAZ8iaRaOHRU5DT0RFUkSHjUxhdmY2MC4xNi4xMDBzc9ZjwItjxYj4aeWw3TPuLGfIoUWjh0VOQ09ERVJEh5RMYXZjNjAuMzEuMTAyIGxpYnZweGfIoUWjiERVUkFUSU9ORIeTMDA6MDA6MDEuMDAwMDAwMDAwAB9DtnVC0+eBAKPegQAAgPAGAJ0BKqAAeAAARwiFhYiFhIgCAgJ1qgP4AgaTjwUQnFLSoTilpUJxS0qE4paVCcUtKhOKWlQnFLSoTilpUJsA/v9NEv/8WFfxYV/FhX/xYV/8/M7txfzmAKOYgQAoABECAAUQrAAYABhYL/QACICBDLAAo5iBAFAAEQIABRCsABgAGFgv9AAIgIEMsACjmIEAeAARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQCgABECAAUQrAAYABhYL/QACICBDLAAo5iBAMgAEQIABRCsABgAGFgv9AAIgIEMsACjmIEA8AARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQEYABECAAUQEBRgAGFgv9AAIgIEMsAAo5iBAUAAEQIABRCsABgAGFgv9AAIgIEMsACjmIEBaAARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQGQABECAAUQrAAYABhYL/QACICBDLAAo5iBAbgAEQIABRCsABgAGFgv9AAIgIEMsACjmIEB4AARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQIIABECAAUQrAAYABhYL/QACICBDLAAo5iBAjAAEQIABRCsABgAGFgv9AAIgIEMsACjmIECWAARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQKAABECAAUQrAAYABhYL/QACICBDLAAo5iBAqgAEQIABRCsABgAGFgv9AAIgIEMsACjmIEC0AARAgAFEBAUYABhYL/QACICBDLAAKOYgQL4ABECAAUQrAAYABhYL/QACICBDLAAo5iBAyAAEQIABRCsABgAGFgv9AAIgIEMsACjmIEDSAARAgAFEKwAGAAYWC/0AAiAgQywAKOYgQNwABECAAUQrAAYABhYL/QACICBDLAAo5iBA5gAEQIABRCsABgAGFgv9AAIgIEMsACjmIEDwAARAgAFEKwAGAAYWC/0AAiAgQywABxTu2uRu4+zgQC3iveBAfGCAZ/wgQM=','base64')});await page.locator('#upload-intro').click();await page.waitForSelector('#intro-preview-wrap video');assert(await page.evaluate(()=>_calls.some(c=>c.type==='upload'&&c.data.type==='video/webm')));
 await page.locator('#intro-kind').selectOption('none');await page.locator('#upload-intro').click();await page.waitForFunction(()=>document.querySelector('#intro-status').textContent.includes('désactivé'));assert.equal(await page.locator('#intro-preview-wrap img').count(),0);
 await page.screenshot({path:path.join(screenshots,'configuration-mobile.png'),fullPage:true});
 await page.locator('#qr-artwork-preview').screenshot({path:path.join(screenshots,'configuration-card.png')});
 const bounds=await page.evaluate(async()=>{
  const results=[];
  for(const plan of ['photo','audio','premium','long']){
   const calls=[],original=CanvasRenderingContext2D.prototype.fillText;
   CanvasRenderingContext2D.prototype.fillText=function(text,x,y,...args){if(y>1180&&this.font.includes('Inter'))calls.push({y,width:this.measureText(text).width,font:this.font});return original.call(this,text,x,y,...args)};
   try{await window.__card.buildPrintCardCanvas({couple_name:'Julie & Thomas',plan,qr_font:'elegant',...(plan==='long'?{print_note:'Un souvenir pour vous '.repeat(8).slice(0,120),print_explanation:'Partagez vos souvenirs avec nous '.repeat(10).slice(0,240)}:{})},location.origin+'/capsule.html?t=example-token');results.push({plan,calls})}finally{CanvasRenderingContext2D.prototype.fillText=original}
  }
  return results;
 });
 for(const result of bounds){assert(result.calls.length);assert(result.calls.every(c=>c.y<=1545&&c.width<=891),JSON.stringify(result));}

 // Organiser messages: retries preserve content, and every download gets a fresh URL.
 await page.evaluate(()=>{
  window._manifest=[{id:'memory1',guest_name:'Alice',media_type:'image',is_available:true,delivery_at:new Date().toISOString(),created_at:new Date().toISOString()}];
  window._messageRows=[{id:'memory1',guest_name:'Alice',media_type:'image',media_path:'owner/memory1/photo.png',message_text:'Un beau souvenir'}];
 });
 await page.evaluate(()=>document.querySelector('[data-owner-tab-link="messages"]').click());await page.locator('#refresh-memories').click();await page.waitForSelector('.memory-row');assert.match(await page.locator('#memory-list').innerText(),/Un beau souvenir/);
 await page.evaluate(()=>window._failManifest=true);await page.locator('#refresh-memories').click();assert.match(await page.locator('#memory-status').innerText(),/Chargement impossible/);assert.match(await page.locator('#memory-list').innerText(),/Un beau souvenir/);
 await page.evaluate(()=>{window._failManifest=false;window._failMessages=true});await page.locator('#refresh-memories').click();assert.match(await page.locator('#memory-status').innerText(),/Chargement impossible/);
 await page.evaluate(()=>window._failMessages=false);await page.locator('#refresh-memories').click();await page.waitForFunction(()=>document.querySelector('#memory-status').textContent==='Souvenirs à jour.');
 await page.evaluate(()=>window._failSigned=true);await page.getByRole('button',{name:'Télécharger',exact:true}).click();assert.match(await page.locator('#memory-list').innerText(),/Téléchargement impossible/);
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export-memories').click()]);assert.match(download.suggestedFilename(),/souvenirs-.*\.zip/);assert.match(await page.locator('#export-status').innerText(),/téléchargés/);await page.evaluate(()=>{window._zipChunks=[];window._zipClosed=false;window.showSaveFilePicker=async()=>{_calls.push({type:'file-picker'});return{createWritable:async()=>({write:async bytes=>_zipChunks.push(Array.from(bytes)),close:async()=>_zipClosed=true,abort:async()=>{}})}}});await page.locator('#export-memories').click();await page.waitForFunction(()=>window._zipClosed);assert.equal(await page.evaluate(()=>_zipChunks[0].slice(0,4).join(',')),'80,75,3,4');assert(await page.evaluate(()=>{const events=_calls.slice(_calls.findLastIndex(c=>c.type==='file-picker'));return events[1].type==='owner_export_bundle'}));
 await page.evaluate(()=>{window.showSaveFilePicker=undefined;window._exportBundle={name:'Big capsule',date:'2027-06-12',messages:[{media_type:'video',guest_name:'Alice',path:'private/large.mp4',bytes:151000000,delivery_at:new Date().toISOString()}]}});await page.locator('#export-memories').click();await page.waitForFunction(()=>document.querySelector('#export-status').textContent.includes('150 Mo'));await page.evaluate(()=>window._exportBundle=null);
 
 await page.evaluate(()=>window._failSigned=false);const before=await page.evaluate(()=>_calls.filter(c=>c.type==='signed').length);await page.getByRole('button',{name:'Recharger le média',exact:true}).click();assert((await page.evaluate(()=>_calls.filter(c=>c.type==='signed').length))>before);
 // Reveal without manual refresh, then expiry and account changes clear private views.
 await page.evaluate(()=>{_revealAt=Date.now()+1500;_manifest=[{id:'due',guest_name:'Bob',media_type:'text',is_available:false,delivery_at:new Date(_revealAt).toISOString(),created_at:new Date().toISOString()}];_messageRows=[{id:'due',guest_name:'Bob',media_type:'text',message_text:'Ouvert automatiquement'}]});await page.locator('#refresh-memories').click();await page.waitForFunction(()=>document.querySelector('#memory-list').textContent.includes('Ouvert automatiquement'));assert(await page.locator('#next-delivery').isHidden());
 await page.evaluate(()=>{localStorage.setItem('reviewExpired','yes')});await page.addInitScript(()=>{if(localStorage.getItem('reviewExpired'))window._usage={state:'expired',quota_bytes:5000000000,used_bytes:0,opens_at:'2020-01-01',closes_at:'2020-01-03',expires_at:'2023-01-01',delivery_before:'2022-07-01'}});await page.reload();await page.waitForSelector('#intro-kind');assert(await page.locator('#share-link').isDisabled());assert(await page.locator('#export-memories').isDisabled());assert.match(await page.locator('#next-delivery').innerText(),/conservation.*terminée/);assert(await page.locator('#capsule-name').isDisabled());await page.evaluate(()=>{localStorage.removeItem('reviewExpired');localStorage.removeItem('logged');_authEvent('SIGNED_OUT',null)});await page.waitForURL('**/auth.html');assert.equal(await page.locator('#memory-list').count(),0);await page.evaluate(()=>localStorage.setItem('logged','yes'));
 // Single-capsule accounts bypass the list, and creation resumes the existing capsule.
 await page.goto(base+'/dashboard.html');await page.waitForURL('**/dashboard.html?slug=*');await page.waitForSelector('#intro-kind');assert(await page.locator('#capsule-list-link').isHidden());
 assert(!/brouillon/i.test(await page.locator('body').innerText()));
 await page.goto(base+'/create.html');await page.waitForURL('**/dashboard.html?slug=*');await page.waitForSelector('#intro-kind');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('testCaps')).length),1);
 // Older accounts keep all of their existing capsules without a new-creation or delete-draft control.
 await page.evaluate(()=>{const caps=JSON.parse(localStorage.getItem('testCaps'));localStorage.setItem('testCaps',JSON.stringify([...caps,{...caps[0],id:'older-capsule',slug:'older-event',status:'draft'}]))});
 await page.goto(base+'/dashboard.html');await page.waitForSelector('.capsule-card');assert.equal(await page.locator('.capsule-card').count(),2);await page.waitForFunction(()=>document.querySelector('[data-capsule-count]').textContent.includes('2 souvenir'));assert.equal(await page.locator('[data-delete-draft]').count(),0);assert.equal(await page.locator('.capsule-new').count(),0);assert(!/brouillon/i.test(await page.locator('body').innerText()));await page.screenshot({path:path.join(screenshots,'account-mobile.png'),fullPage:true});
 for(const width of [390,1280]){await page.setViewportSize({width,height:900});await page.goto(base+'/index.html');assert.match(await page.locator('h1').innerText(),/découvrir/);assert.equal(await page.locator('.pricing-card').nth(1).locator('.pricing-icon i').count(),2);assert.equal(await page.locator('.pricing-card').nth(2).locator('.pricing-icon i').count(),3);assert.equal(await page.locator('.formats-block').count(),0);assert(!(await page.locator('.future-offer').evaluate(e=>e.open)));assert.match(await page.locator('.pricing-launch').innerText(),/restera gratuite/);await page.locator('.future-offer summary').click();await page.locator('.pricing-card').nth(1).hover();assert.equal(await page.locator('.pricing-icon').nth(1).evaluate(e=>getComputedStyle(e).boxShadow),'none');assert.equal(await page.locator('.pricing-icon').nth(1).evaluate(e=>getComputedStyle(e).transform),'none');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(screenshots,'home-'+width+'.png'),fullPage:true})}
 await page.evaluate(()=>{localStorage.removeItem('logged');localStorage.setItem('testCaps','[]')});await page.goto(base+'/create.html');await page.locator('#couple').fill('Stockage bloqué');await page.locator('#wedding_date_display').fill('12/06/'+eventYear);await page.locator('#email').fill('test@example.com');await page.evaluate(()=>Storage.prototype.setItem=()=>{throw new DOMException('Blocked','SecurityError')});await page.locator('button[type=submit]').click();assert.match(await page.locator('#status').innerText(),/empêche de conserver/);assert.equal(await page.locator('#status a').count(),1);
 assert.deepEqual(errors,[]);console.log('PASS: login, signup confirmation, password mismatch/reset/recovery, preserved creation, plan, private preparation controls, activation, capsule list, cumulative icons, responsive layout, optional greetings, activation saves pending edits, autosave ordering and retry, settings, confirmations, single capsule resume and preserved older accounts, message refresh and renewed media links');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
