const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),assert=require('node:assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..');
(async()=>{
 const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://test').pathname;try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(root+p));}catch{res.statusCode=404;res.end();}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:390,height:844}});await context.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({body:'',contentType:'application/javascript'}));
 await context.addInitScript(()=>{
  window._calls=[];window._member=localStorage.getItem('member')==='yes';const now=new Date().toISOString();let capsule={id:'11111111-1111-4111-8111-111111111111',owner_id:'owner',name:'Anne & Paul',date:'2027-06-12',plan:'premium',activation:'free_beta',suspended:false,quota_override:null,messages:12,usage:{state:'scheduled',used_bytes:200000000,quota_bytes:5000000000,expires_at:'2030-06-12T00:00:00Z'}};let backups=[];
  window.supabase={createClient:()=>({auth:{getUser:async()=>({data:{user:localStorage.getItem('logged')?{id:'owner'}:null}}),onAuthStateChange:()=>{},signInWithPassword:async()=>{localStorage.setItem('logged','yes');return{data:{session:{}}};},resetPasswordForEmail:async(email,options)=>{_calls.push({action:'reset',options});return{data:{}};},signOut:async()=>{localStorage.removeItem('logged');}},rpc:async(name,{p_token}={})=>{_calls.push({name,p_token});if(name==='admin_claim'){window._member=true;localStorage.setItem('member','yes');return{data:true};}return{data:window._member};},functions:{invoke:async(name,{body})=>{_calls.push(body);if(body.action==='services')return{data:{configured:{notifications:false,payments:false},notifications_enabled:false,payments_enabled:false}};if(body.action==='overview')return{data:{capsules:[capsule],clients:[{id:'owner',email:'anne@example.com',confirmed:true,created_at:now}],backups}};
   if(body.action==='manage'){capsule.suspended=body.suspended;capsule.quota_override=body.quota;capsule.usage.quota_bytes=body.quota||5000000000;capsule.usage.state=body.suspended?'suspended':'scheduled';}
   if(body.action==='backup')backups=[{id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',label:'Toutes les capsules',state:'ready',created_at:now,total:0,cursor:0}];return{data:{ok:true}};}}})};
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/admin.html');await page.locator('#admin-auth').waitFor({state:'visible'});assert(await page.locator('#admin-content').isHidden());assert(await page.locator('#admin-signup').isHidden());
 await page.locator('#admin-auth a').first().click();await page.waitForURL('**/auth.html?next=admin');assert.match(await page.locator('#auth-title').innerText(),/administration/);assert(await page.locator('#password-field small').isHidden());
 await page.locator('[data-auth-mode=reset]').click();await page.locator('#email').fill('anne@example.com');await page.locator('button[type=submit]').click();assert(await page.evaluate(()=>_calls.some(c=>c.action==='reset'&&c.options.redirectTo.endsWith('auth.html?mode=recovery&next=admin'))));
 await page.locator('[data-auth-mode=login]').click();await page.locator('#password').fill('longpassword123');await page.locator('button[type=submit]').click();await page.waitForURL('**/admin.html');await page.waitForFunction(()=>document.querySelector('#access-message').textContent.includes('ne dispose'));assert(await page.locator('#admin-content').isHidden());
 await page.goto(base+'/admin.html#invite='+'a'.repeat(64));await page.locator('#capsule-cards article').waitFor();assert(!page.url().includes('invite'));assert.equal(await page.evaluate(()=>localStorage.getItem('la_suite_admin_invite')),null);assert(await page.evaluate(()=>_calls.some(c=>c.name==='admin_claim')));
 await page.locator('#search').fill('nobody');assert.equal(await page.locator('#capsule-cards article').count(),0);await page.locator('#search').fill('anne@example.com');assert.equal(await page.locator('#capsule-cards article').count(),1);
 await page.locator('[data-capsule]').click();await page.locator('#detail-suspend').click();await page.locator('#confirm-no').click();assert(!await page.evaluate(()=>_calls.some(c=>c.action==='manage')));
 await page.locator('#detail-suspend').click();await page.locator('#confirm-yes').click();await page.waitForFunction(()=>document.querySelector('#capsule-cards').textContent.includes('Dépôts en pause'));assert(await page.evaluate(()=>_calls.some(c=>c.action==='manage'&&c.suspended)));
 await page.locator('[data-capsule]').click();await page.locator('.admin-quota summary').click();await page.locator('#quota').fill('8');await page.locator('#quota-form button').click();await page.waitForFunction(()=>document.querySelector('#capsule-cards').textContent.includes('8.0 Go'));assert(await page.evaluate(()=>_calls.some(c=>c.action==='manage'&&c.quota===8000000000)));
 await page.locator('[data-tab=clients]').click();assert(await page.locator('#panel-capsules').isHidden());await page.locator('[data-client]').click();assert(await page.locator('#panel-clients').isHidden());
 await page.locator('[data-tab=backups]').click();await page.locator('#backup-all').click();await page.locator('[data-restore]').waitFor();await page.locator('[data-restore]').click();await page.locator('#confirm-no').click();assert(!await page.evaluate(()=>_calls.some(c=>c.action==='restore')));
 await page.locator('[data-restore]').click();await page.locator('#confirm-yes').click();await page.waitForFunction(()=>_calls.some(c=>c.action==='restore'));
 await page.locator('[data-tab=capsules]').click();for(const width of [390,1280]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(process.env.QA_SCREENSHOTS||require('os').tmpdir(),'admin-'+width+'.png'),fullPage:true});}
 assert.deepEqual(errors,[]);await browser.close();server.close();console.log('PASS: admin invitation, isolation, filters, pause confirmation, quota, backups and mobile layout');
})().catch(e=>{console.error(e);process.exit(1)});
